// Italian. Compiled with /utf-8 (see QuestCalibrator.vcxproj).
//
// Glossary, so a term reads the same everywhere:
//   calibration            calibrazione              recalibrate      ricalibra
//   continuous calibration calibrazione continua     headset tracker  tracker del visore
//   chaperone              chaperone                 protect (it)     proteggi / protetto
//   Quest boundary         confine del Quest         base station     stazione base
//   field anchor           ancora di campo           alignment        allineamento
//   reference / target     riferimento / destinazione tracking delay ritardo di tracciamento
//
// The player is addressed as "tu", as SteamVR's Italian interface does.
// Counts are written as "label: N" so no key needs a singular/plural pair.
// Keys are the English exactly as the UI builds it (Localization.h explains
// patterns: {0}, {1}... are the printf values in key order).
#include "LocalizationTables.h"

namespace questcal::i18n
{

const char *const kItalianNativeName = "Italiano";

const Entry kItalian[] = {
	// ---- Window, tabs, footer ----
	{ "Calibration", "Calibrazione" },
	{ "Lighthouse", "Lighthouse" },
	{ "Smoothing", "Smussamento" },
	{ "Lighthouse module is currently not installed. Select it during installation.",
		"Il modulo Lighthouse non è installato. Selezionalo durante l'installazione." },
	{ "Work in progress", "In lavorazione" },
	{ "Arrow keys to move · Enter to select", "Frecce per spostarti · Invio per selezionare" },
	{ "Close the SteamVR dashboard to use the mouse", "Chiudi la dashboard di SteamVR per usare il mouse" },
	{ "Dismiss", "Chiudi" },

	// ---- Continuous calibration state ----
	{ "Off", "Spento" },
	{ "Needs a tracker", "Serve un tracker" },
	{ "Needs setup", "Da configurare" },
	{ "Waiting", "In attesa" },
	{ "Active", "Attiva" },
	{ "Paused", "In pausa" },
	{ "Warming up", "In avvio" },
	{ "Continuous calibration is off.", "La calibrazione continua è disattivata." },
	{ "Continuous calibration needs a headset tracker. Pick one in Settings.",
		"La calibrazione continua richiede un tracker del visore. Sceglilo nelle Impostazioni." },
	{ "Continuous calibration needs the headset tracker set up. Do it in Settings.",
		"La calibrazione continua richiede di configurare il tracker del visore. Fallo nelle Impostazioni." },
	{ "Continuous calibration is waiting. It resumes when tracking is available.",
		"La calibrazione continua è in attesa. Riprende quando il tracciamento è disponibile." },
	{ "Continuous calibration is active.", "La calibrazione continua è attiva." },
	{ "Continuous calibration is waiting. The headset tracker isn't being seen.",
		"La calibrazione continua è in attesa. Il tracker del visore non viene rilevato." },
	{ "Continuous calibration is paused. Readings drifted too far to correct.",
		"La calibrazione continua è in pausa. Lo scostamento è troppo grande da correggere." },
	{ "Continuous calibration is waiting. Tracking is too noisy here.",
		"La calibrazione continua è in attesa. Qui il tracciamento è troppo instabile." },
	{ "Continuous calibration is warming up.", "La calibrazione continua si sta avviando." },

	// ---- Status band ----
	{ "Alignment:", "Allineamento:" },
	{ "Good", "Buono" },
	{ "Usable", "Accettabile" },
	{ "Rough", "Impreciso" },
	{ "Bad", "Scarso" },
	{ "Not measured", "Non misurato" },
	{ "Your trackers won't line up like this. Recalibrate.",
		"Così i tracker non saranno allineati. Ricalibra." },
	{ "Recalibrate to tighten the alignment.", "Ricalibra per migliorare l'allineamento." },
	{ "time is in the future", "l'orario è nel futuro" },
	{ "just now", "proprio ora" },
	{ "%d min ago", "{0} min fa" },
	{ "%.1f h ago", "{0} h fa" },
	{ "%.0f days ago", "{0} giorni fa" },
	{ "adjusted %s", "regolata {0}" },
	{ "calibrated %s", "calibrata {0}" },
	{ "last adjusted %s", "ultima regolazione {0}" },
	{ "maintained continuously", "mantenuta di continuo" },
	{ "calibration time unknown", "ora di calibrazione sconosciuta" },
	{ "Continuous calibration paused", "Calibrazione continua in pausa" },
	{ "Tracking no longer matches the saved alignment. Recalibrate with the headset tracker.",
		"Il tracciamento non corrisponde più all'allineamento salvato. Ricalibra con il tracker del visore." },
	{ "Recalibrate", "Ricalibra" },
	{ "Turn off continuous calibration", "Disattiva la calibrazione continua" },
	{ "Not calibrated yet. Pick a device on each side and press Start calibration.",
		"Non ancora calibrato. Scegli un dispositivo per lato e premi Avvia calibrazione." },

	// Advanced-mode numbers under the verdict.
	{ "Difference: %.1f deg yaw, %.1f deg tilt, %.1f cm position",
		"Differenza: imbardata {0}°, inclinazione {1}°, posizione {2} cm" },
	{ "Solve: %.2f deg / %.1f cm, %+.1f ms%s", "Soluzione: {0}° / {1} cm, {2} ms{3}" },
	{ ", scaled", ", con scala" },
	{ "Scale: %s (condition %.4f, uncertainty %.4f)", "Scala: {0} (condizionamento {1}, incertezza {2})" },
	{ "identifiable", "identificabile" },
	{ "insufficient", "insufficiente" },
	{ "Jumps: %u compensated%s", "Salti compensati: {0}{1}" },
	{ " (tracking gaps seen; recalibrate if alignment looks off)",
		" (interruzioni del tracciamento rilevate; ricalibra se l'allineamento sembra errato)" },
	{ "stale", "da rifare" },
	{ "aging", "datato" },
	{ "fresh", "recente" },
	{ "Drift: %s", "Deriva: {0}" },
	{ "Drift: %s; %u slip%s up to %.1f cm while standing still",
		"Deriva: {0}; scivolamenti da fermo: {1} (fino a {3} cm)" },
	{ "Drift: %s; %u tracking dropout%s with a position change",
		"Deriva: {0}; perdite di tracciamento con spostamento: {1}" },
	{ "Drift: %s; %u slip%s up to %.1f cm while standing still; %u tracking dropout%s with a position change",
		"Deriva: {0}; scivolamenti da fermo: {1} (fino a {3} cm); perdite di tracciamento con spostamento: {4}" },
	{ "Upkeep: scatter %.2f deg / %.1f cm, deviation %.2f deg / %.1f cm, %u corrections",
		"Mantenimento: dispersione {0}° / {1} cm, scostamento {2}° / {3} cm, correzioni: {4}" },
	{ "Upkeep: %u corrections", "Mantenimento: correzioni: {0}" },

	// Warnings above the buttons.
	{ "%s headset isn't connected. Calibration is off until it's back.",
		"Il visore {0} non è collegato. La calibrazione resta disattivata finché non torna." },
	{ "SteamVR isn't accepting the calibration. Restart SteamVR.",
		"SteamVR non accetta la calibrazione. Riavvia SteamVR." },
	{ "The saved calibration doesn't match the connected hardware. Recalibrate.",
		"La calibrazione salvata non corrisponde all'hardware collegato. Ricalibra." },
	{ "The saved calibration is damaged. Recalibrate.", "La calibrazione salvata è danneggiata. Ricalibra." },
	{ "The headset re-centered while QuestCalibrator wasn't watching, so the saved alignment is off. Recalibrate.",
		"Il visore si è ricentrato mentre QuestCalibrator non lo seguiva, quindi l'allineamento salvato è errato. Ricalibra." },
	{ "Calibration disabled. Restart SteamVR or recalibrate.",
		"Calibrazione disattivata. Riavvia SteamVR o ricalibra." },
	{ "QuestCalibrator isn't getting tracking data from SteamVR, so it can't watch for drift. Restart SteamVR.",
		"QuestCalibrator non riceve dati di tracciamento da SteamVR, quindi non può controllare la deriva. Riavvia SteamVR." },
	{ "(host hooks: 005 %s, 006 %s)", "(hook dell'host: 005 {0}, 006 {1})" },
	{ "active", "attivo" },
	{ "missing", "assente" },
	{ "QuestCalibrator %s is ready. Open Settings to install it.",
		"QuestCalibrator {0} è pronto. Apri le Impostazioni per installarlo." },

	// ---- Main screen buttons ----
	{ "Start calibration", "Avvia calibrazione" },
	{ "%d s", "{0} s" },
	{ "How long calibration collects tracking data. Longer can be more accurate.\nMove gently at every setting.",
		"Per quanto tempo la calibrazione raccoglie dati. Più a lungo può essere più precisa.\nMuoviti con delicatezza con qualsiasi durata." },
	{ "Clear calibration", "Cancella calibrazione" },
	{ "Clear this calibration?", "Cancellare questa calibrazione?" },
	{ "Your trackers won't line up until you calibrate again. This also removes the field anchors and the headset tracker setup.",
		"I tracker non saranno allineati finché non calibri di nuovo. Vengono rimosse anche le ancore di campo e la configurazione del tracker del visore." },
	{ "Keep calibration", "Mantieni calibrazione" },
	{ "Identify selected devices", "Identifica i dispositivi" },
	{ "Vibrates or blinks the two selected devices so you can tell which is which.",
		"Fa vibrare o lampeggiare i due dispositivi selezionati, così capisci quale è quale." },
	{ "Update protected chaperone", "Aggiorna il chaperone protetto" },
	{ "Protect chaperone", "Proteggi il chaperone" },
	{ "Saves your current chaperone (SteamVR's walls) and puts it\nback automatically if SteamVR or the headset ever loses it.\nRedrew your chaperone? Press again to protect the new one.\nPrefer the Quest boundary imported fresh each session? Don't use this.",
		"Salva il chaperone attuale (le pareti di SteamVR) e lo ripristina\nautomaticamente se SteamVR o il visore lo perdono.\nHai ridisegnato il chaperone? Premi di nuovo per proteggere quello nuovo.\nPreferisci importare il confine del Quest a ogni sessione? Non usarlo." },
	{ "Add field anchor", "Aggiungi ancora di campo" },
	{ "Aligned in one spot but slightly off in another?\nStand at the bad spot, press this, and do a quick calibration there.\nThat spot gets its own correction, blended in as you walk around.",
		"Allineato in un punto ma leggermente sfasato in un altro?\nMettiti nel punto sbagliato, premi qui e fai una breve calibrazione.\nQuel punto avrà la sua correzione, raccordata mentre ti muovi." },
	{ "Recent activity", "Attività recente" },

	// ---- Device panes ----
	{ "REFERENCE SYSTEM", "SISTEMA DI RIFERIMENTO" },
	{ "TARGET SYSTEM", "SISTEMA DI DESTINAZIONE" },
	{ "Low battery", "Batteria scarica" },
	{ "Rename this device", "Rinomina questo dispositivo" },
	{ "Vibrate or blink this device", "Fai vibrare o lampeggiare questo dispositivo" },
	{ "Hip, Left foot, Chest...", "Anca, Piede sinistro, Petto..." },
	{ "No devices connected", "Nessun dispositivo collegato" },
	{ "No tracked devices found", "Nessun dispositivo tracciato" },
	{ "No trackers found. Turn on a tracker and make sure SteamVR sees it.",
		"Nessun tracker trovato. Accendi un tracker e verifica che SteamVR lo veda." },
	{ "Calibration takes %.0f seconds. The next screen shows how to move.",
		"La calibrazione dura {0} secondi. La schermata successiva mostra come muoverti." },

	// ---- Settings ----
	{ "Language", "Lingua" },
	{ "English", "English" },
	{ "Italiano", "Italiano" },
	{ "Japanese", "Japanese" },
	{ "This translation may not be accurate.", "Questa traduzione potrebbe non essere precisa." },
	{ "Feel free to send any feedback:", "Qualsiasi suggerimento è benvenuto:" },
	{ "Report on GitHub", "Segnala su GitHub" },
	{ "Advanced mode", "Modalità avanzata" },
	{ "Shows calibration measurements, drift readings and extra settings.",
		"Mostra le misure della calibrazione, i valori di deriva e impostazioni aggiuntive." },
	{ "Alignment notifications in VR", "Notifiche di allineamento in VR" },
	{ "A SteamVR notification when the calibration looks off or continuous calibration pauses.",
		"Una notifica di SteamVR quando la calibrazione sembra errata o la calibrazione continua va in pausa." },
	{ "Field anchors", "Ancore di campo" },
	{ "Corrects the alignment in the spots where you added an anchor.",
		"Corregge l'allineamento nei punti in cui hai aggiunto un'ancora." },
	{ "Clear anchors", "Cancella ancore" },
	{ "Keep anchors", "Mantieni ancore" },
	{ "Clear 1 field anchor?", "Cancellare 1 ancora di campo?" },
	{ "Clear %zu field anchors?", "Cancellare {0} ancore di campo?" },
	{ "That spot goes back to the main calibration. The calibration itself is kept.",
		"Quel punto torna alla calibrazione principale. La calibrazione resta." },
	{ "Those spots go back to the main calibration. The calibration itself is kept.",
		"Quei punti tornano alla calibrazione principale. La calibrazione resta." },
	{ "%zu anchor%s saved", "Ancore salvate: {0}" },
	{ "Anchor %zu at (%+.1f, %+.1f): %.1f cm / %.2f deg from base",
		"Ancora {0} in ({1}, {2}): {3} cm / {4}° dalla base" },
	{ "Solve playspace scale (experimental)", "Stima la scala dello spazio di gioco (sperimentale)" },
	{ "Measures whether the two systems disagree on distances. Leave off unless you know you need it.",
		"Misura se i due sistemi misurano le distanze in modo diverso. Lascialo spento se non sai di averne bisogno." },
	{ "Correct for tracking delay", "Compensa il ritardo di tracciamento" },
	{ "Uses the delay between the two systems measured during calibration.",
		"Usa il ritardo tra i due sistemi misurato durante la calibrazione." },
	{ "Manual tracking delay override (debug)", "Ritardo di tracciamento manuale (debug)" },
	{ "Continuous calibration", "Calibrazione continua" },
	{ "Keeps devices aligned while you play, using a tracker strapped to your headset.",
		"Mantiene allineati i dispositivi mentre giochi, usando un tracker fissato al visore." },
	{ "Headset tracker", "Tracker del visore" },
	{ "Method", "Metodo" },
	{ "Standard", "Standard" },
	{ "Legacy", "Legacy" },
	{ "Standard measures where the tracker sits on the headset once,\nthen corrects from every pose. Legacy is OpenVR-SpaceCalibrator's\nmethod: it re-solves from head movement. Try it if Standard keeps pausing.",
		"Standard misura una volta dove si trova il tracker sul visore,\npoi corregge da ogni posa. Legacy è il metodo di OpenVR-SpaceCalibrator:\nricalcola dai movimenti della testa. Provalo se Standard va spesso in pausa." },
	{ "Hide the headset tracker from games", "Nascondi il tracker del visore ai giochi" },
	{ "Moves it far out of reach in games so full-body setups never\nmistake it for a body tracker. Calibration still sees it.",
		"Nei giochi lo sposta lontano, così le configurazioni full-body\nnon lo scambiano per un tracker del corpo. La calibrazione lo vede comunque." },
	{ "Keep tracking delay up to date", "Aggiorna di continuo il ritardo di tracciamento" },
	{ "Re-measures the delay between the two systems during play, using\nthe headset tracker. Off keeps the value from calibration.",
		"Rimisura durante il gioco il ritardo tra i due sistemi, usando\nil tracker del visore. Se spento, usa il valore della calibrazione." },
	{ "Ask before applying each correction", "Chiedi prima di applicare ogni correzione" },
	{ "Each correction waits until you pull a controller trigger.\nRecent activity on the main screen lists each one.",
		"Ogni correzione attende che tu prema un grilletto del controller.\nL'attività recente nella schermata principale le elenca." },
	{ "Strap a tracker to your headset and pick it above.", "Fissa un tracker al visore e sceglilo qui sopra." },
	{ "Recalibrate with the headset tracker (%.0f s)", "Ricalibra con il tracker del visore ({0} s)" },
	{ "Set up headset tracker (%.0f s)", "Configura il tracker del visore ({0} s)" },
	{ "Turn off to let the Quest boundary import win each session;\nthe protected chaperone then only applies when you press Restore.",
		"Spegnilo per dare la precedenza al confine del Quest a ogni sessione;\nil chaperone protetto si applica solo quando premi Ripristina." },
	{ "Restore protected chaperone automatically", "Ripristina automaticamente il chaperone protetto" },
	{ "Only the play area center was saved (no walls), so there's nothing to restore automatically.",
		"È stato salvato solo il centro dell'area di gioco (senza pareti), quindi non c'è nulla da ripristinare automaticamente." },
	{ "%zu wall%s, %.1f x %.1f m, protected %s", "Pareti: {0}, {2} × {3} m, protetto {4}" },
	{ "age unknown", "data sconosciuta" },
	{ "Restore chaperone now", "Ripristina ora il chaperone" },
	{ "Automatic updates", "Aggiornamenti automatici" },
	{ "Downloads verified updates. Close Steam before installing them.",
		"Scarica gli aggiornamenti verificati. Chiudi Steam prima di installarli." },
	{ "Checking for updates...", "Ricerca aggiornamenti..." },
	{ "Downloading %s  %u%%", "Download di {0}  {1}%" },
	{ "You're up to date (%s)", "Sei aggiornato ({0})" },
	{ "Version %s is downloaded and verified", "La versione {0} è scaricata e verificata" },
	{ "Update check failed", "Controllo aggiornamenti non riuscito" },
	{ "Update check failed: %s", "Controllo aggiornamenti non riuscito: {0}" },
	{ "%s is a test build and doesn't update itself", "{0} è una build di prova e non si aggiorna da sola" },
	{ "Not checked yet", "Non ancora controllato" },
	{ "Install %s", "Installa {0}" },
	{ "Check again", "Controlla di nuovo" },
	{ "Detailed calibration logging", "Registro dettagliato della calibrazione" },
	{ "Records extra tracking and calibration details. Saved diagnostics remove your name and folder paths.",
		"Registra più dettagli su tracciamento e calibrazione. Le diagnostiche salvate rimuovono il tuo nome e i percorsi delle cartelle." },
	{ "Save diagnostics file", "Salva file di diagnostica" },
	{ "Diagnostics saved to %s", "Diagnostica salvata in {0}" },
	{ "Motion demo credits", "Crediti delle animazioni" },
	{ "Edit calibration (advanced)", "Modifica calibrazione (avanzato)" },

	// Calibration editor.
	{ "ROTATION (DEGREES)", "ROTAZIONE (GRADI)" },
	{ "Yaw", "Imbardata" },
	{ "Pitch", "Beccheggio" },
	{ "Roll", "Rollio" },
	{ "TRANSLATION (CENTIMETERS)", "TRASLAZIONE (CENTIMETRI)" },
	{ "SCALE", "SCALA" },
	{ "These values can't be applied. Use plain numbers within range. The saved calibration is unchanged.",
		"Questi valori non si possono applicare. Usa numeri semplici entro i limiti. La calibrazione salvata non è cambiata." },
	{ "Save calibration", "Salva calibrazione" },
	{ "Close", "Chiudi" },

	// ---- Guided calibration ----
	{ "Step 1 of 3", "Passo 1 di 3" },
	{ "Step 2 of 3", "Passo 2 di 3" },
	{ "Stand where the trackers look misaligned.", "Mettiti dove i tracker sembrano disallineati." },
	{ "Hold the controller against the visor.", "Tieni il controller appoggiato alla visiera." },
	{ "Keep the tracker fixed to your headset.", "Tieni il tracker fissato al visore." },
	{ "Hold the controller against the wrist tracker.", "Tieni il controller appoggiato al tracker del polso." },
	{ "Hold the controller upright, with the trigger side against the front of your headset. Keep it in place as you turn and tilt your head for %.0f seconds.",
		"Tieni il controller dritto, con il lato del grilletto contro la parte anteriore del visore. Tienilo fermo mentre giri e inclini la testa per {0} secondi." },
	{ "Move your head gently for %.0f seconds, keeping your body relaxed. Keep the tracker sensors uncovered.",
		"Muovi la testa con delicatezza per {0} secondi, con il corpo rilassato. Non coprire i sensori del tracker." },
	{ "Hold the controller against the wrist tracker with your other hand. Move both in a figure eight, gently turning and tilting, for %.0f seconds.",
		"Con l'altra mano tieni il controller contro il tracker del polso. Muovili insieme disegnando un otto, girandoli e inclinandoli con delicatezza, per {0} secondi." },
	{ "Look left and right", "Guarda a destra e a sinistra" },
	{ "Look up and down", "Guarda in alto e in basso" },
	{ "Tilt side to side", "Inclina da un lato all'altro" },
	{ "Bring the controller to the wrist tracker", "Avvicina il controller al tracker del polso" },
	{ "Turn and tilt as you move in a figure eight", "Gira e inclina mentre disegni un otto" },
	{ "Rest the controller against the visor", "Appoggia il controller alla visiera" },
	{ "Motion demos couldn't load. Reinstall QuestCalibrator to restore them.",
		"Impossibile caricare le animazioni. Reinstalla QuestCalibrator per ripristinarle." },
	{ "Reference device", "Dispositivo di riferimento" },
	{ "Target device", "Dispositivo di destinazione" },
	{ "%s is tracking", "{0}: tracciato" },
	{ "%s isn't tracking. Wake it or bring it into view.",
		"{0} non è tracciato. Riattivalo o portalo in vista." },
	{ "Replay", "Rivedi" },
	{ "Pause demo", "Pausa demo" },
	{ "Play demo", "Riproduci demo" },
	{ "Start", "Avvia" },
	{ "Start anyway", "Avvia comunque" },
	{ "Cancel", "Annulla" },
	{ "Starting in %d...", "Inizio tra {0}..." },
	{ "Look around slowly.", "Guardati intorno lentamente." },
	{ "Look left and right, then up and down. Gently tilt your head to each side. Keep the tracker in view of the base stations.",
		"Guarda a destra e a sinistra, poi in alto e in basso. Inclina delicatamente la testa da entrambi i lati. Tieni il tracker in vista delle stazioni base." },
	{ "Keep both devices firmly together.", "Tieni i due dispositivi ben uniti." },
	{ "Move both devices in a figure eight, gently turning and tilting as you go. Keep them firmly together and in view of their tracking cameras or base stations.",
		"Muovi i due dispositivi disegnando un otto, girandoli e inclinandoli con delicatezza. Tienili ben uniti e in vista delle telecamere di tracciamento o delle stazioni base." },
	{ "Motion variety", "Varietà del movimento" },
	{ "Movement speed", "Velocità del movimento" },
	{ "Tracker stability", "Stabilità del tracker" },
	{ "Device stability", "Stabilità dei dispositivi" },
	{ "Measuring...", "Misurazione..." },
	{ "Enough variety", "Varietà sufficiente" },
	{ "Keep turning and tilting", "Continua a girare e inclinare" },
	{ "Good pace", "Ritmo giusto" },
	{ "Move more slowly", "Muoviti più lentamente" },
	{ "Moving together", "Si muovono insieme" },
	{ "Tracker is shifting on the headset", "Il tracker si sposta sul visore" },
	{ "Hold them tighter together", "Tienili più uniti" },
	{ "%.0f s left", "{0} s rimanenti" },
	{ "Calibrating...", "Calibrazione in corso..." },
	{ "Hide details", "Nascondi dettagli" },
	{ "Show details", "Mostra dettagli" },
	{ "Try again", "Riprova" },
	{ "Done", "Fatto" },

	// ---- Run outcomes ----
	{ "Calibration complete", "Calibrazione completata" },
	{ "Calibration failed", "Calibrazione non riuscita" },
	{ "Calibration stopped", "Calibrazione interrotta" },
	{ "Calibration cancelled", "Calibrazione annullata" },
	{ "Done, but the headset tracker wasn't set up", "Fatto, ma il tracker del visore non è stato configurato" },
	{ "Check that the tracker positions line up in VR.", "Controlla in VR che le posizioni dei tracker siano allineate." },
	{ "The alignment is rough.", "L'allineamento è impreciso." },
	{ "The alignment may need another pass.", "L'allineamento potrebbe richiedere un altro passaggio." },
	{ "Try again with slower motion, turning and tilting in different directions.",
		"Riprova muovendoti più lentamente, girando e inclinando in direzioni diverse." },
	{ "Check the tracker positions in VR. Try again if they look off.",
		"Controlla le posizioni dei tracker in VR. Riprova se sembrano sfasate." },
	{ "Applied for this session, but it couldn't be saved. Recalibrate after restarting.",
		"Applicata per questa sessione, ma non è stato possibile salvarla. Ricalibra dopo il riavvio." },
	{ "Headset tracker set up, so continuous calibration can keep it that way.",
		"Tracker del visore configurato: la calibrazione continua può mantenere l'allineamento." },
	{ "Headset tracker set up.", "Tracker del visore configurato." },
	{ "Turn on continuous calibration in Settings to use it.", "Per usarlo, attiva la calibrazione continua nelle Impostazioni." },
	{ "The headset tracker's identity couldn't be verified, so its previous setup is kept.",
		"Non è stato possibile verificare l'identità del tracker del visore, quindi resta la configurazione precedente." },
	{ "Try again. If it repeats, restart SteamVR.", "Riprova. Se si ripete, riavvia SteamVR." },
	{ "The headset tracker's position couldn't be measured consistently, so its previous setup is kept.",
		"Non è stato possibile misurare in modo coerente la posizione del tracker del visore, quindi resta la configurazione precedente." },
	{ "The headset tracker's position couldn't be measured consistently.",
		"Non è stato possibile misurare in modo coerente la posizione del tracker del visore." },
	{ "Recalibrate with the headset tracker and look around more slowly.",
		"Ricalibra con il tracker del visore e guardati intorno più lentamente." },

	// Why a solve was refused.
	{ "The devices didn't rotate far enough.", "I dispositivi non hanno ruotato abbastanza." },
	{ "Use wider turns while keeping both devices fixed together.", "Fai rotazioni più ampie tenendo i dispositivi uniti." },
	{ "The devices only rotated in one direction.", "I dispositivi hanno ruotato in una sola direzione." },
	{ "The devices didn't rotate in enough directions.", "I dispositivi non hanno ruotato in abbastanza direzioni." },
	{ "Turn and tilt both devices together in different directions.",
		"Gira e inclina insieme i due dispositivi in direzioni diverse." },
	{ "Turn and tilt both devices together, then try again.", "Gira e inclina insieme i due dispositivi, poi riprova." },
	{ "The devices' rotation readings didn't match closely enough.", "Le misure di rotazione dei dispositivi non coincidevano abbastanza." },
	{ "Hold them firmly together and try again.", "Tienili ben uniti e riprova." },
	{ "The devices' position readings didn't match closely enough.", "Le misure di posizione dei dispositivi non coincidevano abbastanza." },
	{ "Move slowly and keep both devices in clear view, then try again.",
		"Muoviti lentamente e tieni entrambi i dispositivi ben in vista, poi riprova." },
	{ "Couldn't measure the tracking delay between the devices.", "Impossibile misurare il ritardo di tracciamento tra i dispositivi." },
	{ "Keep turning both devices together until the timer finishes.",
		"Continua a girare insieme i due dispositivi fino alla fine del timer." },
	{ "Almost no tracking data arrived.", "Non sono arrivati quasi dati di tracciamento." },
	{ "Check that both devices are tracking, then try again.",
		"Verifica che entrambi i dispositivi siano tracciati, poi riprova." },
	{ "Some tracking data was corrupt.", "Alcuni dati di tracciamento erano danneggiati." },
	{ "Try again; restart SteamVR if it repeats.", "Riprova; se si ripete, riavvia SteamVR." },
	{ "Playspace scale couldn't be determined from this motion.", "Da questo movimento non è stato possibile determinare la scala dello spazio di gioco." },
	{ "Cover a larger area, or turn off Solve playspace scale in Settings.",
		"Copri un'area più ampia, oppure disattiva Stima la scala dello spazio di gioco nelle Impostazioni." },
	{ "Something went wrong inside QuestCalibrator.", "Si è verificato un errore interno in QuestCalibrator." },
	{ "Save a diagnostics file in Settings and send it with your report.",
		"Salva un file di diagnostica nelle Impostazioni e invialo con la segnalazione." },
	{ "The calibration result wasn't usable.", "Il risultato della calibrazione non era utilizzabile." },
	{ "Try again with smooth motion around the room.", "Riprova con movimenti fluidi nella stanza." },

	// Why a run stopped.
	{ "Some tracking data was dropped: the PC couldn't keep up.",
		"Alcuni dati di tracciamento sono andati persi: il PC non riusciva a stare al passo." },
	{ "Try again; close capture or recording software if it repeats.",
		"Riprova; se si ripete, chiudi i programmi di acquisizione o registrazione." },
	{ "%s's tracking reset during the measurement.", "Il tracciamento di {0} si è reimpostato durante la misura." },
	{ "Let tracking settle for a few seconds, then start again.",
		"Lascia stabilizzare il tracciamento per qualche secondo, poi ricomincia." },
	{ "The reference device", "Il dispositivo di riferimento" },
	{ "The target device", "Il dispositivo di destinazione" },
	{ "QuestCalibrator can't talk to SteamVR.", "QuestCalibrator non riesce a comunicare con SteamVR." },
	{ "Restart SteamVR. If it repeats, re-run the installer.",
		"Riavvia SteamVR. Se si ripete, esegui di nuovo il programma di installazione." },
	{ "No reference device is selected.", "Nessun dispositivo di riferimento selezionato." },
	{ "No target device is selected.", "Nessun dispositivo di destinazione selezionato." },
	{ "Pick a device that's switched on.", "Scegli un dispositivo acceso." },
	{ "%s isn't tracking.", "{0} non è tracciato." },
	{ "Check it's awake and in view of its tracking cameras or base stations, then try again.",
		"Verifica che sia attivo e in vista delle telecamere di tracciamento o delle stazioni base, poi riprova." },
	{ "Check it's awake and visible to its base stations, then try again.",
		"Verifica che sia attivo e visibile alle stazioni base, poi riprova." },
	{ "A device changed tracking system as the run started.",
		"Un dispositivo ha cambiato sistema di tracciamento all'avvio." },
	{ "Re-pick both devices and start again.", "Scegli di nuovo entrambi i dispositivi e ricomincia." },
	{ "SteamVR stopped reporting one of the devices.", "SteamVR ha smesso di segnalare uno dei dispositivi." },
	{ "Wake or reconnect it, then try again.", "Riattivalo o ricollegalo, poi riprova." },
	{ "The reference device must be on the headset's tracking system.",
		"Il dispositivo di riferimento deve appartenere al sistema di tracciamento del visore." },
	{ "Pick the headset or one of its controllers as the reference.",
		"Scegli come riferimento il visore o uno dei suoi controller." },
	{ "Lost contact with SteamVR mid-run.", "Contatto con SteamVR perso durante la misura." },
	{ "Restart SteamVR and try again.", "Riavvia SteamVR e riprova." },
	{ "%s was replaced by another device during the measurement.",
		"{0} è stato sostituito da un altro dispositivo durante la misura." },
	{ "Could not verify the identity of %s during the measurement.",
		"Impossibile verificare l'identità di {0} durante la misura." },
	{ "Keep both devices powered and try again.", "Tieni accesi entrambi i dispositivi e riprova." },
	{ "%s stopped tracking mid-run.", "{0} ha smesso di essere tracciato durante la misura." },
	{ "Keep it tracking for the whole countdown.", "Mantienilo tracciato per tutto il conto alla rovescia." },
	{ "Keep it in view of its base stations for the whole countdown.",
		"Tienilo in vista delle stazioni base per tutto il conto alla rovescia." },
	{ "Pick a reference and a target from two different tracking systems.",
		"Scegli riferimento e destinazione da due sistemi di tracciamento diversi." },
	{ "Anchors need the same reference and target systems as the current calibration. Pick those devices first.",
		"Le ancore richiedono gli stessi sistemi di riferimento e destinazione della calibrazione attuale. Scegli prima quei dispositivi." },
	{ "The headset isn't showing up in SteamVR, so the tracker position can't be measured yet.",
		"Il visore non compare in SteamVR, quindi non è ancora possibile misurare la posizione del tracker." },
	{ "The headset tracker isn't connected. Switch it on, then try again.",
		"Il tracker del visore non è collegato. Accendilo e riprova." },

	// Field anchors.
	{ "Anchor not added", "Ancora non aggiunta" },
	{ "Anchor added", "Ancora aggiunta" },
	{ "This spot is too far off from your calibration for a small correction.",
		"Questo punto è troppo lontano dalla calibrazione per una piccola correzione." },
	{ "Run a full calibration instead.", "Esegui invece una calibrazione completa." },
	{ "You already have 8 anchors.", "Hai già 8 ancore." },
	{ "Add this one within 1 m of an existing anchor to replace it, or clear the anchors in Settings.",
		"Aggiungila entro 1 m da un'ancora esistente per sostituirla, oppure cancella le ancore nelle Impostazioni." },
	{ "It couldn't be saved.", "Non è stato possibile salvarla." },
	{ "Restart QuestCalibrator and try again.", "Riavvia QuestCalibrator e riprova." },
	{ "This spot now has its own correction, blended in as you walk around.",
		"Questo punto ora ha la sua correzione, raccordata mentre ti muovi." },

	// ---- Runtime monitors (activity feed and VR notifications) ----
	{ "Your calibration looks off. Recalibrate.", "La calibrazione sembra errata. Ricalibra." },
	{ "QuestCalibrator: your calibration looks off. Recalibrate.",
		"QuestCalibrator: la calibrazione sembra errata. Ricalibra." },
	{ "A correction was too large to be safe and was skipped. If this keeps happening, recalibrate.",
		"Una correzione era troppo grande per essere sicura ed è stata saltata. Se continua a succedere, ricalibra." },
	{ "Correction ready. Pull a trigger to apply it.", "Correzione pronta. Premi un grilletto per applicarla." },
	{ "Trigger pulled; applying the correction.", "Grilletto premuto; applico la correzione." },
	{ "Continuous calibration paused: readings drifted too far from the calibration to correct safely.",
		"Calibrazione continua in pausa: le misure si sono allontanate troppo dalla calibrazione per correggerle in sicurezza." },
	{ "QuestCalibrator: continuous calibration paused; readings drifted too far to correct safely. Recalibrate with the headset tracker to resume.",
		"QuestCalibrator: calibrazione continua in pausa; lo scostamento è troppo grande per correggerlo in sicurezza. Ricalibra con il tracker del visore per riprendere." },
	{ "Continuous calibration paused: readings are inconsistent with the headset tracker measurement.",
		"Calibrazione continua in pausa: le misure non sono coerenti con quella del tracker del visore." },
	{ "QuestCalibrator: continuous calibration paused; readings are inconsistent. Recalibrate with the headset tracker to resume.",
		"QuestCalibrator: calibrazione continua in pausa; le misure non sono coerenti. Ricalibra con il tracker del visore per riprendere." },
	{ "Tracking is noisy here; continuous calibration is waiting and resumes on its own.",
		"Qui il tracciamento è instabile; la calibrazione continua è in attesa e riprenderà da sola." },
	{ "QuestCalibrator: tracking is noisy here. Continuous calibration is waiting and resumes on its own.",
		"QuestCalibrator: qui il tracciamento è instabile. La calibrazione continua è in attesa e riprenderà da sola." },
	{ "Continuous calibration resumed.", "Calibrazione continua ripresa." },
	{ "Headset tracker not tracking; continuous calibration waiting.",
		"Tracker del visore non tracciato; calibrazione continua in attesa." },
	{ "Headset tracker back; continuous calibration warming up.",
		"Tracker del visore di nuovo visibile; calibrazione continua in avvio." },

	// ---- Chaperone ----
	{ "Check your room boundaries", "Controlla i confini della stanza" },
	{ "QuestCalibrator saves and restores your SteamVR chaperone. Tracking drift can still move the chaperone walls away from your real walls.",
		"QuestCalibrator salva e ripristina il chaperone di SteamVR. La deriva del tracciamento può comunque allontanare le sue pareti da quelle reali." },
	{ "Keep the Quest boundary turned on too. A protected chaperone doesn't guarantee that your play area is clear or correctly aligned.",
		"Tieni attivo anche il confine del Quest. Un chaperone protetto non garantisce che l'area di gioco sia libera o allineata correttamente." },
	{ "Before playing, check that the chaperone walls match your room and leave enough space to move safely, especially when dancing.",
		"Prima di giocare, controlla che le pareti del chaperone corrispondano alla stanza e lascino spazio per muoverti in sicurezza, soprattutto se balli." },
	{ "Protect chaperone (%d s)", "Proteggi il chaperone ({0} s)" },
	{ "Chaperone saved without walls, so auto-restore stays off until Room Setup adds some.",
		"Chaperone salvato senza pareti: il ripristino automatico resta spento finché Configurazione stanza non ne aggiunge." },
	{ "Chaperone saved: %u wall%s, %.1f x %.1f m.", "Chaperone salvato: pareti: {0}, {2} × {3} m." },
	{ "Chaperone restored.", "Chaperone ripristinato." },
	{ "Couldn't check the protected chaperone: SteamVR's chaperone setup isn't available right now.",
		"Impossibile controllare il chaperone protetto: la configurazione del chaperone di SteamVR non è disponibile al momento." },
	{ "Couldn't read the current chaperone, so the protected one wasn't changed.",
		"Impossibile leggere il chaperone attuale, quindi quello protetto non è stato modificato." },
	{ "The protected chaperone was saved for a different headset, so it was switched off. Press Protect chaperone again on the main screen.",
		"Il chaperone protetto era stato salvato per un altro visore, quindi è stato disattivato. Premi di nuovo Proteggi il chaperone nella schermata principale." },
	{ "The protected chaperone is missing information about the room it was saved in, so it was switched off. Press Protect chaperone again on the main screen.",
		"Al chaperone protetto mancano informazioni sulla stanza in cui è stato salvato, quindi è stato disattivato. Premi di nuovo Proteggi il chaperone nella schermata principale." },
	{ "The headset re-centered, so the protected chaperone no longer lines up and was turned off. Protect it again from the main screen.",
		"Il visore si è ricentrato e il chaperone protetto non è più allineato, quindi è stato disattivato. Proteggilo di nuovo dalla schermata principale." },
	{ "The headset re-centered while QuestCalibrator couldn't follow it, so the protected chaperone was switched off. Press Protect chaperone again on the main screen.",
		"Il visore si è ricentrato mentre QuestCalibrator non poteva seguirlo, quindi il chaperone protetto è stato disattivato. Premi di nuovo Proteggi il chaperone nella schermata principale." },
	{ "The protected chaperone belonged to the previous calibration and was turned off. Protect it again from the main screen.",
		"Il chaperone protetto apparteneva alla calibrazione precedente ed è stato disattivato. Proteggilo di nuovo dalla schermata principale." },
	{ "A headset re-center was too large to compensate safely. Recalibrate before continuing.",
		"Un ricentramento del visore era troppo grande per compensarlo in sicurezza. Ricalibra prima di continuare." },
	{ "The headset re-centered while QuestCalibrator couldn't follow it. The calibration and the protected chaperone are off until you recalibrate.",
		"Il visore si è ricentrato mentre QuestCalibrator non poteva seguirlo. Calibrazione e chaperone protetto restano disattivati finché non ricalibri." },
	{ "The headset re-centered while QuestCalibrator couldn't follow it. The calibration is off until you recalibrate.",
		"Il visore si è ricentrato mentre QuestCalibrator non poteva seguirlo. La calibrazione resta disattivata finché non ricalibri." },
	{ "Couldn't protect the chaperone. The headset re-centered since the last calibration. Recalibrate first.",
		"Impossibile proteggere il chaperone. Il visore si è ricentrato dopo l'ultima calibrazione. Ricalibra prima." },
	{ "Couldn't protect the chaperone because SteamVR's chaperone isn't available. Restart SteamVR and try again.",
		"Impossibile proteggere il chaperone perché quello di SteamVR non è disponibile. Riavvia SteamVR e riprova." },
	{ "Couldn't protect the chaperone because the headset isn't showing up in SteamVR. Try again once it's connected.",
		"Impossibile proteggere il chaperone perché il visore non compare in SteamVR. Riprova quando è collegato." },
	{ "Couldn't protect the chaperone. The calibration was made with a different headset system. Recalibrate first.",
		"Impossibile proteggere il chaperone. La calibrazione è stata fatta con un altro sistema di visore. Ricalibra prima." },
	{ "Couldn't protect the chaperone because the headset isn't tracking yet. Put it on and try again.",
		"Impossibile proteggere il chaperone perché il visore non è ancora tracciato. Indossalo e riprova." },
	{ "Couldn't read the chaperone walls from SteamVR. Try again.",
		"Impossibile leggere le pareti del chaperone da SteamVR. Riprova." },
	{ "The chaperone changed while it was being saved. Try again.",
		"Il chaperone è cambiato durante il salvataggio. Riprova." },
	{ "Couldn't protect the chaperone because SteamVR has no usable play area. Set up your room in SteamVR, then try again.",
		"Impossibile proteggere il chaperone perché SteamVR non ha un'area di gioco utilizzabile. Configura la stanza in SteamVR, poi riprova." },
	{ "Couldn't protect the chaperone because the PC clock looks wrong. Check the date and time, then try again.",
		"Impossibile proteggere il chaperone perché l'orologio del PC sembra errato. Controlla data e ora, poi riprova." },
	{ "Couldn't protect the chaperone because the previous one couldn't be switched off first, so nothing was changed.",
		"Impossibile proteggere il chaperone perché non è stato possibile disattivare prima quello precedente, quindi non è cambiato nulla." },
	{ "Couldn't restore the chaperone: the protected chaperone is damaged. Protect it again.",
		"Impossibile ripristinare il chaperone: quello protetto è danneggiato. Proteggilo di nuovo." },
	{ "Couldn't restore the chaperone: the headset isn't reporting to SteamVR yet.",
		"Impossibile ripristinare il chaperone: il visore non comunica ancora con SteamVR." },
	{ "Couldn't restore the chaperone yet: the headset hasn't been tracked this session. Put it on and try again.",
		"Non è ancora possibile ripristinare il chaperone: il visore non è stato tracciato in questa sessione. Indossalo e riprova." },
	{ "Couldn't restore the chaperone: SteamVR's chaperone setup isn't available right now.",
		"Impossibile ripristinare il chaperone: la configurazione del chaperone di SteamVR non è disponibile al momento." },
	{ "Couldn't restore the chaperone: SteamVR rejected the update.",
		"Impossibile ripristinare il chaperone: SteamVR ha rifiutato l'aggiornamento." },
	{ "Couldn't verify the restored chaperone. Check it in SteamVR Room Setup before relying on it.",
		"Impossibile verificare il chaperone ripristinato. Controllalo in Configurazione stanza di SteamVR prima di farci affidamento." },
	{ "The calibration profile and protected chaperone were saved at different revisions. Chaperone auto-restore is disabled until you capture it again.",
		"Il profilo di calibrazione e il chaperone protetto sono stati salvati in momenti diversi. Il ripristino automatico del chaperone è disattivato finché non lo proteggi di nuovo." },
	{ "The protected chaperone has no complete headset/universe baseline. It has been disarmed; capture it again before enabling auto-restore.",
		"Il chaperone protetto non ha un riferimento completo del visore. È stato disattivato; proteggilo di nuovo prima di attivare il ripristino automatico." },
	{ "The protected chaperone belongs to a different reference tracking system. It has been disarmed; capture it again for this profile.",
		"Il chaperone protetto appartiene a un altro sistema di tracciamento di riferimento. È stato disattivato; proteggilo di nuovo per questo profilo." },

	// ---- Saving and loading ----
	{ "Couldn't clear the calibration, so it's still saved. Restart QuestCalibrator and try again.",
		"Impossibile cancellare la calibrazione, che resta salvata. Riavvia QuestCalibrator e riprova." },
	{ "Couldn't read the saved calibration, so it was left as it is. Restart QuestCalibrator. If this repeats, save a diagnostics file in Settings and report it.",
		"Impossibile leggere la calibrazione salvata, che è stata lasciata com'era. Riavvia QuestCalibrator. Se si ripete, salva un file di diagnostica nelle Impostazioni e segnalalo." },
	{ "Couldn't read QuestCalibrator's settings, so they were left as they are. Restart QuestCalibrator. If this repeats, save a diagnostics file in Settings and report it.",
		"Impossibile leggere le impostazioni di QuestCalibrator, che sono state lasciate com'erano. Riavvia QuestCalibrator. Se si ripete, salva un file di diagnostica nelle Impostazioni e segnalalo." },
	{ "Couldn't save the calibration because the saved one couldn't be read. It was left untouched so it can be recovered.",
		"Impossibile salvare la calibrazione perché quella salvata non è leggibile. È stata lasciata intatta per poterla recuperare." },
	{ "Couldn't save the calibration because QuestCalibrator's settings couldn't be read. They were left untouched so they can be recovered.",
		"Impossibile salvare la calibrazione perché le impostazioni di QuestCalibrator non sono leggibili. Sono state lasciate intatte per poterle recuperare." },
	{ "Couldn't save the calibration because settings from an older version haven't been moved over safely yet. Restart QuestCalibrator and try again.",
		"Impossibile salvare la calibrazione perché le impostazioni di una versione precedente non sono ancora state trasferite in sicurezza. Riavvia QuestCalibrator e riprova." },
	{ "Couldn't save the calibration because it failed a safety check. Recalibrate.",
		"Impossibile salvare la calibrazione perché non ha superato un controllo di sicurezza. Ricalibra." },
	{ "Couldn't save the calibration. It will be lost when QuestCalibrator closes.",
		"Impossibile salvare la calibrazione. Andrà persa alla chiusura di QuestCalibrator." },
	{ "Couldn't save the calibration because the rotation values aren't valid.",
		"Impossibile salvare la calibrazione perché i valori di rotazione non sono validi." },
	{ "Couldn't save QuestCalibrator's settings because the saved calibration couldn't be read. Nothing was changed, so both can still be recovered.",
		"Impossibile salvare le impostazioni perché la calibrazione salvata non è leggibile. Non è cambiato nulla, quindi entrambe sono recuperabili." },
	{ "Couldn't save QuestCalibrator's settings because the saved ones couldn't be read. They were left untouched so they can be recovered.",
		"Impossibile salvare le impostazioni perché quelle salvate non sono leggibili. Sono state lasciate intatte per poterle recuperare." },
	{ "Couldn't save QuestCalibrator's settings because the protected chaperone failed a safety check. Protect it again.",
		"Impossibile salvare le impostazioni perché il chaperone protetto non ha superato un controllo di sicurezza. Proteggilo di nuovo." },
	{ "Couldn't save QuestCalibrator's settings. Changes will be lost when it closes.",
		"Impossibile salvare le impostazioni. Le modifiche andranno perse alla chiusura." },
	{ "Error loading calibration profile: %s", "Errore nel caricamento del profilo di calibrazione: {0}" },
	{ "Error loading application settings: %s", "Errore nel caricamento delle impostazioni: {0}" },
	{ "The profile is preserved, not overwritten.", "Il profilo è conservato, non sovrascritto." },
	{ "Settings changes will not save until this is fixed.", "Le modifiche alle impostazioni non verranno salvate finché il problema non è risolto." },
	{ "To start over, delete the Config value under %s", "Per ricominciare da zero, elimina il valore Config in {0}" },
	{ "To start over, delete the Settings value under %s", "Per ricominciare da zero, elimina il valore Settings in {0}" },
	{ "The live profile has invalid tracking-system identities and was disabled before sending it to the driver",
		"Il profilo attivo ha identità di sistema di tracciamento non valide ed è stato disattivato prima di inviarlo al driver" },
	{ "The live calibration contains invalid numeric values and was disabled before sending it to the driver",
		"La calibrazione attiva contiene valori numerici non validi ed è stata disattivata prima di inviarla al driver" },
	{ "Couldn't find the local application data folder.", "Impossibile trovare la cartella dei dati locali delle applicazioni." },
	{ "Couldn't create the diagnostics file in %s.", "Impossibile creare il file di diagnostica in {0}." },
	{ "Couldn't finish writing the diagnostics file.", "Impossibile completare la scrittura del file di diagnostica." },

	// ---- Updates ----
	{ "QuestCalibrator %s is a prerelease. Automatic updates follow stable releases only, so this build will not update itself. Install a stable release by hand to rejoin them.",
		"QuestCalibrator {0} è una versione preliminare. Gli aggiornamenti automatici seguono solo le versioni stabili, quindi questa build non si aggiornerà da sola. Installa a mano una versione stabile per riceverli di nuovo." },
	{ "Checking GitHub for updates", "Ricerca aggiornamenti su GitHub" },
	{ "QuestCalibrator is up to date", "QuestCalibrator è aggiornato" },
	{ "Downloading QuestCalibrator %s", "Download di QuestCalibrator {0}" },
	{ "QuestCalibrator %s is ready to install", "QuestCalibrator {0} è pronto per l'installazione" },
	{ "The update check could not start.", "Impossibile avviare il controllo degli aggiornamenti." },
	{ "The update check failed unexpectedly.", "Il controllo degli aggiornamenti non è riuscito per un errore imprevisto." },
	{ "Update check cancelled.", "Controllo aggiornamenti annullato." },
	{ "Update download cancelled.", "Download dell'aggiornamento annullato." },
	{ "%s failed (Windows error %s).", "{0}: operazione non riuscita (errore di Windows {1})." },
	{ "Opening the update connection", "Apertura della connessione di aggiornamento" },
	{ "Setting update timeouts", "Impostazione dei timeout" },
	{ "Connecting to GitHub", "Connessione a GitHub" },
	{ "Creating the GitHub request", "Creazione della richiesta a GitHub" },
	{ "Securing GitHub redirects", "Protezione dei reindirizzamenti di GitHub" },
	{ "Requesting the update", "Richiesta dell'aggiornamento" },
	{ "Reading the update response", "Lettura della risposta" },
	{ "Downloading the update package", "Download del pacchetto" },
	{ "Starting the update helper", "Avvio dell'assistente di aggiornamento" },
	{ "GitHub returned HTTP %d.", "GitHub ha risposto HTTP {0}." },
	{ "GitHub returned invalid UTF-8.", "GitHub ha restituito UTF-8 non valido." },
	{ "GitHub returned an invalid release list.", "GitHub ha restituito un elenco di versioni non valido." },
	{ "GitHub returned an unexpectedly large release list.", "GitHub ha restituito un elenco di versioni troppo grande." },
	{ "Windows did not provide a local app-data folder.", "Windows non ha fornito una cartella dei dati locali delle app." },
	{ "Windows PowerShell could not be located.", "Impossibile trovare Windows PowerShell." },
	{ "The release package URL is invalid.", "L'URL del pacchetto non è valido." },
	{ "The release package URL is not HTTPS.", "L'URL del pacchetto non usa HTTPS." },
	{ "The release package URL does not use github.com.", "L'URL del pacchetto non usa github.com." },
	{ "The release package digest is invalid.", "L'impronta del pacchetto non è valida." },
	{ "The update package could not be saved.", "Impossibile salvare il pacchetto di aggiornamento." },
	{ "The update package is larger than GitHub reported.", "Il pacchetto di aggiornamento è più grande di quanto indicato da GitHub." },
	{ "The update package download was incomplete.", "Il download del pacchetto di aggiornamento è incompleto." },
	{ "The update path contains an unsupported character.", "Il percorso dell'aggiornamento contiene un carattere non supportato." },
	{ "The update folder could not be created (system error %d).",
		"Impossibile creare la cartella dell'aggiornamento (errore di sistema {0})." },
	{ "The downloaded package failed SHA-256 verification.", "Il pacchetto scaricato non ha superato la verifica SHA-256." },
	{ "The verified update package could not be saved (system error %d).",
		"Impossibile salvare il pacchetto verificato (errore di sistema {0})." },
	{ "No verified update is ready to install.", "Nessun aggiornamento verificato pronto da installare." },
	{ "The downloaded update no longer passes SHA-256 verification.",
		"L'aggiornamento scaricato non supera più la verifica SHA-256." },
	{ "The update helper could not be created.", "Impossibile creare l'assistente di aggiornamento." },
	{ "The newest release has no trusted release page.", "La versione più recente non ha una pagina di rilascio attendibile." },
	{ "The newest release points outside the QuestCalibrator repository.",
		"La versione più recente punta fuori dal repository di QuestCalibrator." },
	{ "The newest release has no install package.", "La versione più recente non ha un pacchetto di installazione." },
	{ "The newest release contains duplicate install packages.",
		"La versione più recente contiene pacchetti di installazione duplicati." },
	{ "The newest release does not contain %s.", "La versione più recente non contiene {0}." },
	{ "The newest release package has invalid metadata.", "Il pacchetto della versione più recente ha metadati non validi." },
	{ "The newest release package has no valid SHA-256 digest.",
		"Il pacchetto della versione più recente non ha un'impronta SHA-256 valida." },
	{ "The newest release package points outside the QuestCalibrator repository.",
		"Il pacchetto della versione più recente punta fuori dal repository di QuestCalibrator." },

	// ---- Lighthouse tab ----
	{ "No Lighthouse devices", "Nessun dispositivo Lighthouse" },
	{ "Turn on a tracker or controller that uses base stations.",
		"Accendi un tracker o un controller che usa le stazioni base." },
	{ "Waiting for SteamVR's log", "In attesa del registro di SteamVR" },
	{ "Base stations appear here once SteamVR has written %s",
		"Le stazioni base compaiono qui dopo che SteamVR ha scritto {0}" },
	{ "its vrserver log.", "il suo registro vrserver." },
	{ "BASE STATIONS", "STAZIONI BASE" },
	{ "None named yet. Each base station appears as SteamVR reports it.",
		"Ancora nessuna. Ogni stazione base compare quando SteamVR la segnala." },
	{ "id not logged yet", "id non ancora registrato" },
	{ "No reports yet", "Nessuna segnalazione" },
	{ "Seen by %d of %d", "Vista da {0} su {1}" },
	{ "No dropouts this session", "Nessuna interruzione in questa sessione" },
	{ "Dropped out %u time%s", "Interruzioni: {0}" },
	{ "Dropped out %u time%s · the last one left %u time%s", "Interruzioni: {0} · ultima rimasta: {2}" },
	{ "IN VIEW OF EACH DEVICE", "VISTE DA OGNI DISPOSITIVO" },
	{ "Not in the log yet", "Non ancora nel registro" },
	{ "%d of %d in view", "{0} su {1} in vista" },
	{ "no dropouts", "nessuna interruzione" },
	{ "%u dropout%s", "interruzioni: {0}" },
	{ "%u dropout%s, %u full loss%s", "interruzioni: {0}, perdite totali: {2}" },
	{ "In view: no base station", "In vista: nessuna stazione base" },
	{ "In view: %s", "In vista: {0}" },
	{ "Last change: %s", "Ultima variazione: {0}" },
	{ "Tracking restarted %u time%s", "Riavvii del tracciamento: {0}" },
	// What last happened to a device, from LighthouseVisibility.
	{ "tracking again from %s", "di nuovo tracciato da {0}" },
	{ "back to %d stations with %s", "di nuovo {0} stazioni con {1}" },
	{ "lost its last station %s", "ha perso l'ultima stazione {0}" },
	{ "down to one station %s after losing %s", "solo la stazione {0} dopo aver perso {1}" },
	{ "sees no base station", "non vede nessuna stazione base" },
	{ "started a new solution from %s", "nuovo tracciamento avviato da {0}" },
	{ "could not start tracking from %s", "impossibile avviare il tracciamento da {0}" },
	{ "1 drift check this session was skipped because a base station had just changed.",
		"In questa sessione 1 controllo della deriva è stato saltato perché una stazione base era appena cambiata." },
	{ "%u drift checks this session were skipped because a base station had just changed.",
		"Controlli della deriva saltati in questa sessione perché una stazione base era appena cambiata: {0}." },
	{ "Base station changes haven't affected drift checks this session.",
		"In questa sessione i cambi delle stazioni base non hanno influito sui controlli della deriva." },
	{ "Read from %s", "Letto da {0}" },

	// Names shown as they are.
	{ "VividNightmareUnleashed", "VividNightmareUnleashed" },
	{ "Jinxxy", "Jinxxy" },
	{ "OpenVR-SpaceCalibrator", "OpenVR-SpaceCalibrator" },
};

const size_t kItalianCount = sizeof kItalian / sizeof kItalian[0];

} // namespace questcal::i18n
