// Japanese. Compiled with /utf-8 (see QuestCalibrator.vcxproj).
//
// Glossary, so a term reads the same everywhere:
//   calibration           キャリブレーション     recalibrate      再キャリブレーション
//   continuous calibration 連続キャリブレーション  headset tracker  ヘッドセットトラッカー
//   chaperone             シャペロン             protect (it)     保護
//   Quest boundary        Quest の境界線          base station     ベースステーション
//   field anchor          フィールドアンカー       alignment        位置合わせ
//   reference / target    基準 / 対象             tracking delay   トラッキング遅延
//
// Keys are the English exactly as the UI builds it (Localization.h explains
// patterns: {0}, {1}... are the printf values in key order).
#include "LocalizationTables.h"

namespace questcal::i18n
{

const char *const kJapaneseNativeName = "日本語";

const Entry kJapanese[] = {
	// ---- Window, tabs, footer ----
	{ "Calibration", "キャリブレーション" },
	{ "Lighthouse", "Lighthouse" },
	{ "Smoothing", "スムージング" },
	{ "Lighthouse module is currently not installed. Select it during installation.",
		"Lighthouse モジュールはインストールされていません。インストール時に選択してください。" },
	{ "Work in progress", "開発中" },
	{ "Arrow keys to move · Enter to select", "矢印キーで移動・Enter で決定" },
	{ "Close the SteamVR dashboard to use the mouse", "マウスを使うには SteamVR ダッシュボードを閉じてください" },
	{ "Dismiss", "閉じる" },

	// ---- Continuous calibration state ----
	{ "Off", "オフ" },
	{ "Needs a tracker", "トラッカーが必要" },
	{ "Needs setup", "要セットアップ" },
	{ "Waiting", "待機中" },
	{ "Active", "動作中" },
	{ "Paused", "一時停止" },
	{ "Warming up", "準備中" },
	{ "Continuous calibration is off.", "連続キャリブレーションはオフです。" },
	{ "Continuous calibration needs a headset tracker. Pick one in Settings.",
		"連続キャリブレーションにはヘッドセットトラッカーが必要です。設定で選択してください。" },
	{ "Continuous calibration needs the headset tracker set up. Do it in Settings.",
		"連続キャリブレーションにはヘッドセットトラッカーのセットアップが必要です。設定から行ってください。" },
	{ "Continuous calibration is waiting. It resumes when tracking is available.",
		"連続キャリブレーションは待機中です。トラッキングが使えるようになると再開します。" },
	{ "Continuous calibration is active.", "連続キャリブレーションは動作中です。" },
	{ "Continuous calibration is waiting. The headset tracker isn't being seen.",
		"連続キャリブレーションは待機中です。ヘッドセットトラッカーが検出されていません。" },
	{ "Continuous calibration is paused. Readings drifted too far to correct.",
		"連続キャリブレーションは一時停止中です。ずれが大きすぎて補正できません。" },
	{ "Continuous calibration is waiting. Tracking is too noisy here.",
		"連続キャリブレーションは待機中です。この場所ではトラッキングが不安定です。" },
	{ "Continuous calibration is warming up.", "連続キャリブレーションは準備中です。" },

	// ---- Status band ----
	{ "Alignment:", "位置合わせ：" },
	{ "Good", "良好" },
	{ "Usable", "使用可" },
	{ "Rough", "やや不正確" },
	{ "Bad", "不良" },
	{ "Not measured", "未測定" },
	{ "Your trackers won't line up like this. Recalibrate.",
		"このままではトラッカーの位置が合いません。再キャリブレーションしてください。" },
	{ "Recalibrate to tighten the alignment.", "位置合わせの精度を上げるには再キャリブレーションしてください。" },
	{ "time is in the future", "時刻が未来になっています" },
	{ "just now", "たった今" },
	{ "%d min ago", "{0} 分前" },
	{ "%.1f h ago", "{0} 時間前" },
	{ "%.0f days ago", "{0} 日前" },
	{ "adjusted %s", "調整：{0}" },
	{ "calibrated %s", "キャリブレーション：{0}" },
	{ "last adjusted %s", "最終調整：{0}" },
	{ "maintained continuously", "連続して維持中" },
	{ "calibration time unknown", "キャリブレーション時刻不明" },
	{ "Continuous calibration paused", "連続キャリブレーションを一時停止しました" },
	{ "Tracking no longer matches the saved alignment. Recalibrate with the headset tracker.",
		"トラッキングが保存された位置合わせと一致しなくなりました。ヘッドセットトラッカーで再キャリブレーションしてください。" },
	{ "Recalibrate", "再キャリブレーション" },
	{ "Turn off continuous calibration", "連続キャリブレーションをオフ" },
	{ "Not calibrated yet. Pick a device on each side and press Start calibration.",
		"まだキャリブレーションされていません。左右それぞれでデバイスを選び、「キャリブレーション開始」を押してください。" },

	// Advanced-mode numbers under the verdict.
	{ "Difference: %.1f deg yaw, %.1f deg tilt, %.1f cm position", "差：ヨー {0}°、傾き {1}°、位置 {2} cm" },
	{ "Solve: %.2f deg / %.1f cm, %+.1f ms%s", "解：{0}° / {1} cm、{2} ms{3}" },
	{ ", scaled", "、スケールあり" },
	{ "Scale: %s (condition %.4f, uncertainty %.4f)", "スケール：{0}（条件数 {1}、不確かさ {2}）" },
	{ "identifiable", "推定可能" },
	{ "insufficient", "不十分" },
	{ "Jumps: %u compensated%s", "ジャンプ：{0} 回補正{1}" },
	{ " (tracking gaps seen; recalibrate if alignment looks off)",
		"（トラッキングの途切れあり。ずれて見える場合は再キャリブレーション）" },
	{ "stale", "要更新" },
	{ "aging", "やや古い" },
	{ "fresh", "良好" },
	{ "Drift: %s", "ドリフト：{0}" },
	{ "Drift: %s; %u slip%s up to %.1f cm while standing still",
		"ドリフト：{0}、静止中のずれ {1} 回（最大 {3} cm）" },
	{ "Drift: %s; %u tracking dropout%s with a position change",
		"ドリフト：{0}、位置が変わるトラッキング途切れ {1} 回" },
	{ "Drift: %s; %u slip%s up to %.1f cm while standing still; %u tracking dropout%s with a position change",
		"ドリフト：{0}、静止中のずれ {1} 回（最大 {3} cm）、位置が変わるトラッキング途切れ {4} 回" },
	{ "Upkeep: scatter %.2f deg / %.1f cm, deviation %.2f deg / %.1f cm, %u corrections",
		"維持：ばらつき {0}° / {1} cm、偏差 {2}° / {3} cm、補正 {4} 回" },
	{ "Upkeep: %u corrections", "維持：補正 {0} 回" },

	// Warnings above the buttons.
	{ "%s headset isn't connected. Calibration is off until it's back.",
		"{0} ヘッドセットが接続されていません。再接続されるまでキャリブレーションはオフです。" },
	{ "SteamVR isn't accepting the calibration. Restart SteamVR.",
		"SteamVR がキャリブレーションを受け付けていません。SteamVR を再起動してください。" },
	{ "The saved calibration doesn't match the connected hardware. Recalibrate.",
		"保存されたキャリブレーションが接続中の機器と一致しません。再キャリブレーションしてください。" },
	{ "The saved calibration is damaged. Recalibrate.",
		"保存されたキャリブレーションが破損しています。再キャリブレーションしてください。" },
	{ "The headset re-centered while QuestCalibrator wasn't watching, so the saved alignment is off. Recalibrate.",
		"QuestCalibrator が見ていない間にヘッドセットが再センタリングされたため、保存された位置合わせがずれています。再キャリブレーションしてください。" },
	{ "Calibration disabled. Restart SteamVR or recalibrate.",
		"キャリブレーションは無効です。SteamVR を再起動するか、再キャリブレーションしてください。" },
	{ "QuestCalibrator isn't getting tracking data from SteamVR, so it can't watch for drift. Restart SteamVR.",
		"QuestCalibrator が SteamVR からトラッキングデータを受け取れていないため、ドリフトを監視できません。SteamVR を再起動してください。" },
	{ "(host hooks: 005 %s, 006 %s)", "（ホストフック：005 {0}、006 {1}）" },
	{ "active", "有効" },
	{ "missing", "なし" },
	{ "QuestCalibrator %s is ready. Open Settings to install it.",
		"QuestCalibrator {0} の準備ができました。設定からインストールしてください。" },

	// ---- Main screen buttons ----
	{ "Start calibration", "キャリブレーション開始" },
	{ "%d s", "{0} 秒" },
	{ "How long calibration collects tracking data. Longer can be more accurate.\nMove gently at every setting.",
		"キャリブレーションでトラッキングデータを集める時間です。長いほど精度が上がることがあります。\nどの設定でもゆっくり動かしてください。" },
	{ "Clear calibration", "キャリブレーションを消去" },
	{ "Clear this calibration?", "このキャリブレーションを消去しますか？" },
	{ "Your trackers won't line up until you calibrate again. This also removes the field anchors and the headset tracker setup.",
		"もう一度キャリブレーションするまでトラッカーの位置は合いません。フィールドアンカーとヘッドセットトラッカーのセットアップも削除されます。" },
	{ "Keep calibration", "キャリブレーションを残す" },
	{ "Identify selected devices", "選択中のデバイスを確認" },
	{ "Vibrates or blinks the two selected devices so you can tell which is which.",
		"選択中の 2 台のデバイスを振動・点滅させ、どれがどれか分かるようにします。" },
	{ "Update protected chaperone", "保護したシャペロンを更新" },
	{ "Protect chaperone", "シャペロンを保護" },
	{ "Saves your current chaperone (SteamVR's walls) and puts it\nback automatically if SteamVR or the headset ever loses it.\nRedrew your chaperone? Press again to protect the new one.\nPrefer the Quest boundary imported fresh each session? Don't use this.",
		"現在のシャペロン（SteamVR の壁）を保存し、\nSteamVR やヘッドセットが失ったときに自動で戻します。\nシャペロンを描き直したら、もう一度押して新しいものを保護してください。\nQuest の境界線を毎回取り込みたい場合は使わないでください。" },
	{ "Add field anchor", "フィールドアンカーを追加" },
	{ "Aligned in one spot but slightly off in another?\nStand at the bad spot, press this, and do a quick calibration there.\nThat spot gets its own correction, blended in as you walk around.",
		"ある場所では合っているのに、別の場所では少しずれていますか？\nずれている場所に立ってこれを押し、その場で短いキャリブレーションを行ってください。\nその場所専用の補正が作られ、歩き回ると滑らかに切り替わります。" },
	{ "Recent activity", "最近のアクティビティ" },

	// ---- Device panes ----
	{ "REFERENCE SYSTEM", "基準システム" },
	{ "TARGET SYSTEM", "対象システム" },
	{ "Low battery", "バッテリー残量低下" },
	{ "Rename this device", "このデバイスの名前を変更" },
	{ "Vibrate or blink this device", "このデバイスを振動・点滅させる" },
	{ "Hip, Left foot, Chest...", "腰、左足、胸…" },
	{ "No devices connected", "接続されたデバイスはありません" },
	{ "No tracked devices found", "トラッキング中のデバイスが見つかりません" },
	{ "No trackers found. Turn on a tracker and make sure SteamVR sees it.",
		"トラッカーが見つかりません。トラッカーの電源を入れ、SteamVR に認識されているか確認してください。" },
	{ "Calibration takes %.0f seconds. The next screen shows how to move.",
		"キャリブレーションは {0} 秒かかります。動かし方は次の画面で説明します。" },

	// ---- Settings ----
	{ "Language", "言語" },
	{ "English", "English" },
	{ "This translation may not be accurate.", "この翻訳は正確でない場合があります。" },
	{ "Feel free to send any feedback:", "ご意見・ご指摘はお気軽にお寄せください：" },
	{ "Report on GitHub", "GitHub で報告" },
	{ "Advanced mode", "詳細モード" },
	{ "Shows calibration measurements, drift readings and extra settings.",
		"キャリブレーションの測定値、ドリフトの数値、追加の設定を表示します。" },
	{ "Alignment notifications in VR", "VR 内の位置合わせ通知" },
	{ "A SteamVR notification when the calibration looks off or continuous calibration pauses.",
		"キャリブレーションのずれや連続キャリブレーションの一時停止を、SteamVR の通知で知らせます。" },
	{ "Field anchors", "フィールドアンカー" },
	{ "Corrects the alignment in the spots where you added an anchor.",
		"アンカーを追加した場所で位置合わせを補正します。" },
	{ "Clear anchors", "アンカーを消去" },
	{ "Keep anchors", "アンカーを残す" },
	{ "Clear 1 field anchor?", "フィールドアンカーを 1 件消去しますか？" },
	{ "Clear %zu field anchors?", "フィールドアンカーを {0} 件消去しますか？" },
	{ "That spot goes back to the main calibration. The calibration itself is kept.",
		"その場所はメインのキャリブレーションに戻ります。キャリブレーション自体は残ります。" },
	{ "Those spots go back to the main calibration. The calibration itself is kept.",
		"それらの場所はメインのキャリブレーションに戻ります。キャリブレーション自体は残ります。" },
	{ "%zu anchor%s saved", "{0} 件のアンカーを保存済み" },
	{ "Anchor %zu at (%+.1f, %+.1f): %.1f cm / %.2f deg from base",
		"アンカー {0}（{1}, {2}）：基準から {3} cm / {4}°" },
	{ "Solve playspace scale (experimental)", "プレイスペースのスケールを推定（実験的）" },
	{ "Measures whether the two systems disagree on distances. Leave off unless you know you need it.",
		"2 つのシステムで距離の測り方が違うかどうかを測定します。必要な場合以外はオフのままにしてください。" },
	{ "Correct for tracking delay", "トラッキング遅延を補正" },
	{ "Uses the delay between the two systems measured during calibration.",
		"キャリブレーション中に測定した、2 つのシステム間の遅延を使います。" },
	{ "Manual tracking delay override (debug)", "トラッキング遅延を手動で指定（デバッグ）" },
	{ "Continuous calibration", "連続キャリブレーション" },
	{ "Keeps devices aligned while you play, using a tracker strapped to your headset.",
		"ヘッドセットに固定したトラッカーを使い、プレイ中もデバイスの位置を合わせ続けます。" },
	{ "Headset tracker", "ヘッドセットトラッカー" },
	{ "Method", "方式" },
	{ "Standard", "標準" },
	{ "Legacy", "レガシー" },
	{ "Standard measures where the tracker sits on the headset once,\nthen corrects from every pose. Legacy is OpenVR-SpaceCalibrator's\nmethod: it re-solves from head movement. Try it if Standard keeps pausing.",
		"標準方式は、トラッカーがヘッドセットのどこにあるかを一度測定し、\nその後はすべての姿勢から補正します。レガシーは OpenVR-SpaceCalibrator の\n方式で、頭の動きから推定し直します。標準方式が頻繁に止まる場合に試してください。" },
	{ "Hide the headset tracker from games", "ヘッドセットトラッカーをゲームから隠す" },
	{ "Moves it far out of reach in games so full-body setups never\nmistake it for a body tracker. Calibration still sees it.",
		"ゲーム内では遠くへ移動させ、フルボディ設定で\n体のトラッカーと間違われないようにします。キャリブレーションからは見えたままです。" },
	{ "Keep tracking delay up to date", "トラッキング遅延を常に更新" },
	{ "Re-measures the delay between the two systems during play, using\nthe headset tracker. Off keeps the value from calibration.",
		"プレイ中もヘッドセットトラッカーを使って、2 つのシステム間の遅延を\n測り直します。オフにするとキャリブレーション時の値を使います。" },
	{ "Ask before applying each correction", "補正ごとに確認する" },
	{ "Each correction waits until you pull a controller trigger.\nRecent activity on the main screen lists each one.",
		"補正はコントローラーのトリガーを引くまで適用されません。\nメイン画面の「最近のアクティビティ」に表示されます。" },
	{ "Strap a tracker to your headset and pick it above.", "ヘッドセットにトラッカーを固定し、上で選択してください。" },
	{ "Recalibrate with the headset tracker (%.0f s)", "ヘッドセットトラッカーで再キャリブレーション（{0} 秒）" },
	{ "Set up headset tracker (%.0f s)", "ヘッドセットトラッカーをセットアップ（{0} 秒）" },
	{ "Turn off to let the Quest boundary import win each session;\nthe protected chaperone then only applies when you press Restore.",
		"オフにすると、毎回 Quest の境界線の取り込みが優先されます。\n保護したシャペロンは「復元」を押したときだけ適用されます。" },
	{ "Restore protected chaperone automatically", "保護したシャペロンを自動で復元" },
	{ "Only the play area center was saved (no walls), so there's nothing to restore automatically.",
		"プレイエリアの中心だけが保存されている（壁なし）ため、自動で復元するものはありません。" },
	{ "%zu wall%s, %.1f x %.1f m, protected %s", "壁 {0} 面、{2} × {3} m、保護：{4}" },
	{ "age unknown", "時期不明" },
	{ "Restore chaperone now", "今すぐシャペロンを復元" },
	{ "Automatic updates", "自動アップデート" },
	{ "Downloads verified updates. Close Steam before installing them.",
		"検証済みのアップデートをダウンロードします。インストール前に Steam を終了してください。" },
	{ "Checking for updates...", "アップデートを確認中…" },
	{ "Downloading %s  %u%%", "{0} をダウンロード中  {1}%" },
	{ "You're up to date (%s)", "最新版です（{0}）" },
	{ "Version %s is downloaded and verified", "バージョン {0} をダウンロードして検証しました" },
	{ "Update check failed", "アップデートの確認に失敗しました" },
	{ "Update check failed: %s", "アップデートの確認に失敗しました：{0}" },
	{ "%s is a test build and doesn't update itself", "{0} はテスト版のため自動更新されません" },
	{ "Not checked yet", "未確認" },
	{ "Install %s", "{0} をインストール" },
	{ "Check again", "再確認" },
	{ "Detailed calibration logging", "詳細なキャリブレーションログ" },
	{ "Records extra tracking and calibration details. Saved diagnostics remove your name and folder paths.",
		"トラッキングとキャリブレーションの詳細を記録します。保存した診断ファイルからは名前とフォルダーのパスが除かれます。" },
	{ "Save diagnostics file", "診断ファイルを保存" },
	{ "Diagnostics saved to %s", "診断ファイルを保存しました：{0}" },
	{ "Motion demo credits", "モーションデモのクレジット" },
	{ "Edit calibration (advanced)", "キャリブレーションを編集（上級者向け）" },

	// Calibration editor.
	{ "ROTATION (DEGREES)", "回転（度）" },
	{ "Yaw", "ヨー" },
	{ "Pitch", "ピッチ" },
	{ "Roll", "ロール" },
	{ "TRANSLATION (CENTIMETERS)", "移動（cm）" },
	{ "SCALE", "スケール" },
	{ "These values can't be applied. Use plain numbers within range. The saved calibration is unchanged.",
		"この値は適用できません。範囲内の数値を入力してください。保存されたキャリブレーションは変更されていません。" },
	{ "Save calibration", "キャリブレーションを保存" },
	{ "Close", "閉じる" },

	// ---- Guided calibration ----
	{ "Step 1 of 3", "ステップ 1/3" },
	{ "Step 2 of 3", "ステップ 2/3" },
	{ "Stand where the trackers look misaligned.", "トラッカーがずれて見える場所に立ってください。" },
	{ "Hold the controller against the visor.", "コントローラーをバイザーに当ててください。" },
	{ "Keep the tracker fixed to your headset.", "トラッカーをヘッドセットに固定したままにしてください。" },
	{ "Hold the controller against the wrist tracker.", "コントローラーを手首のトラッカーに当ててください。" },
	{ "Hold the controller upright, with the trigger side against the front of your headset. Keep it in place as you turn and tilt your head for %.0f seconds.",
		"コントローラーを立てて、トリガー側をヘッドセットの前面に当ててください。そのまま {0} 秒間、頭をひねったり傾けたりしてください。" },
	{ "Move your head gently for %.0f seconds, keeping your body relaxed. Keep the tracker sensors uncovered.",
		"体の力を抜いて、{0} 秒間ゆっくり頭を動かしてください。トラッカーのセンサーを覆わないでください。" },
	{ "Hold the controller against the wrist tracker with your other hand. Move both in a figure eight, gently turning and tilting, for %.0f seconds.",
		"もう一方の手でコントローラーを手首のトラッカーに当ててください。{0} 秒間、両方を 8の字に動かしながら、ゆっくりひねったり傾けたりしてください。" },
	{ "Look left and right", "左右を見る" },
	{ "Look up and down", "上下を見る" },
	{ "Tilt side to side", "左右に傾ける" },
	{ "Bring the controller to the wrist tracker", "コントローラーを手首のトラッカーに当てる" },
	{ "Turn and tilt as you move in a figure eight", "8の字に動かしながらひねって傾ける" },
	{ "Rest the controller against the visor", "コントローラーをバイザーに当てる" },
	{ "Motion demos couldn't load. Reinstall QuestCalibrator to restore them.",
		"モーションデモを読み込めませんでした。QuestCalibrator を再インストールしてください。" },
	{ "Reference device", "基準デバイス" },
	{ "Target device", "対象デバイス" },
	{ "%s is tracking", "{0}：トラッキング中" },
	{ "%s isn't tracking. Wake it or bring it into view.",
		"{0} がトラッキングされていません。スリープを解除するか、見える位置に移動してください。" },
	{ "Replay", "もう一度再生" },
	{ "Pause demo", "デモを一時停止" },
	{ "Play demo", "デモを再生" },
	{ "Start", "開始" },
	{ "Start anyway", "このまま開始" },
	{ "Cancel", "キャンセル" },
	{ "Starting in %d...", "{0} 秒後に開始…" },
	{ "Look around slowly.", "ゆっくり周りを見回してください。" },
	{ "Look left and right, then up and down. Gently tilt your head to each side. Keep the tracker in view of the base stations.",
		"左右、次に上下を見てください。頭を左右にゆっくり傾けてください。トラッカーがベースステーションから見える状態を保ってください。" },
	{ "Keep both devices firmly together.", "2 つのデバイスをしっかり合わせたままにしてください。" },
	{ "Move both devices in a figure eight, gently turning and tilting as you go. Keep them firmly together and in view of their tracking cameras or base stations.",
		"2 つのデバイスを 8の字に動かしながら、ゆっくりひねったり傾けたりしてください。しっかり合わせたまま、トラッキングカメラやベースステーションから見える位置に保ってください。" },
	{ "Motion variety", "動きの多様さ" },
	{ "Movement speed", "動く速さ" },
	{ "Tracker stability", "トラッカーの安定性" },
	{ "Device stability", "デバイスの安定性" },
	{ "Measuring...", "測定中…" },
	{ "Enough variety", "十分です" },
	{ "Keep turning and tilting", "ひねりと傾けを続けてください" },
	{ "Good pace", "ちょうどよい速さ" },
	{ "Move more slowly", "もっとゆっくり動かしてください" },
	{ "Moving together", "一緒に動いています" },
	{ "Tracker is shifting on the headset", "トラッカーがヘッドセット上でずれています" },
	{ "Hold them tighter together", "もっとしっかり合わせてください" },
	{ "%.0f s left", "残り {0} 秒" },
	{ "Calibrating...", "キャリブレーション中…" },
	{ "Hide details", "詳細を隠す" },
	{ "Show details", "詳細を表示" },
	{ "Try again", "もう一度" },
	{ "Done", "完了" },

	// ---- Run outcomes ----
	{ "Calibration complete", "キャリブレーション完了" },
	{ "Calibration failed", "キャリブレーションに失敗しました" },
	{ "Calibration stopped", "キャリブレーションを中止しました" },
	{ "Calibration cancelled", "キャリブレーションをキャンセルしました" },
	{ "Done, but the headset tracker wasn't set up", "完了しましたが、ヘッドセットトラッカーはセットアップされませんでした" },
	{ "Check that the tracker positions line up in VR.", "VR 内でトラッカーの位置が合っているか確認してください。" },
	{ "The alignment is rough.", "位置合わせの精度が低めです。" },
	{ "The alignment may need another pass.", "位置合わせをもう一度行う必要があるかもしれません。" },
	{ "Try again with slower motion, turning and tilting in different directions.",
		"もっとゆっくり、いろいろな方向にひねったり傾けたりして、もう一度お試しください。" },
	{ "Check the tracker positions in VR. Try again if they look off.",
		"VR 内でトラッカーの位置を確認し、ずれていればもう一度お試しください。" },
	{ "Applied for this session, but it couldn't be saved. Recalibrate after restarting.",
		"このセッションには適用しましたが、保存できませんでした。再起動後に再キャリブレーションしてください。" },
	{ "Headset tracker set up, so continuous calibration can keep it that way.",
		"ヘッドセットトラッカーをセットアップしました。連続キャリブレーションで位置合わせを維持できます。" },
	{ "Headset tracker set up.", "ヘッドセットトラッカーをセットアップしました。" },
	{ "Turn on continuous calibration in Settings to use it.", "使うには設定で連続キャリブレーションをオンにしてください。" },
	{ "The headset tracker's identity couldn't be verified, so its previous setup is kept.",
		"ヘッドセットトラッカーを識別できなかったため、以前のセットアップを残しました。" },
	{ "Try again. If it repeats, restart SteamVR.", "もう一度お試しください。繰り返す場合は SteamVR を再起動してください。" },
	{ "The headset tracker's position couldn't be measured consistently, so its previous setup is kept.",
		"ヘッドセットトラッカーの位置を安定して測定できなかったため、以前のセットアップを残しました。" },
	{ "The headset tracker's position couldn't be measured consistently.",
		"ヘッドセットトラッカーの位置を安定して測定できませんでした。" },
	{ "Recalibrate with the headset tracker and look around more slowly.",
		"ヘッドセットトラッカーで再キャリブレーションし、もっとゆっくり見回してください。" },

	// Why a solve was refused.
	{ "The devices didn't rotate far enough.", "デバイスの回転が足りませんでした。" },
	{ "Use wider turns while keeping both devices fixed together.", "2 つのデバイスを固定したまま、もっと大きく回してください。" },
	{ "The devices only rotated in one direction.", "デバイスが 1 方向にしか回転しませんでした。" },
	{ "The devices didn't rotate in enough directions.", "デバイスを回した方向が足りませんでした。" },
	{ "Turn and tilt both devices together in different directions.",
		"2 つのデバイスを一緒に、いろいろな方向へひねったり傾けたりしてください。" },
	{ "Turn and tilt both devices together, then try again.",
		"2 つのデバイスを一緒にひねったり傾けたりしてから、もう一度お試しください。" },
	{ "The devices' rotation readings didn't match closely enough.", "2 つのデバイスの回転の測定値が十分に一致しませんでした。" },
	{ "Hold them firmly together and try again.", "しっかり合わせて、もう一度お試しください。" },
	{ "The devices' position readings didn't match closely enough.", "2 つのデバイスの位置の測定値が十分に一致しませんでした。" },
	{ "Move slowly and keep both devices in clear view, then try again.",
		"ゆっくり動かし、両方のデバイスがよく見える状態を保って、もう一度お試しください。" },
	{ "Couldn't measure the tracking delay between the devices.", "デバイス間のトラッキング遅延を測定できませんでした。" },
	{ "Keep turning both devices together until the timer finishes.",
		"タイマーが終わるまで、2 つのデバイスを一緒に回し続けてください。" },
	{ "Almost no tracking data arrived.", "トラッキングデータがほとんど届きませんでした。" },
	{ "Check that both devices are tracking, then try again.",
		"両方のデバイスがトラッキングされているか確認して、もう一度お試しください。" },
	{ "Some tracking data was corrupt.", "一部のトラッキングデータが壊れていました。" },
	{ "Try again; restart SteamVR if it repeats.", "もう一度お試しください。繰り返す場合は SteamVR を再起動してください。" },
	{ "Playspace scale couldn't be determined from this motion.", "この動きからはプレイスペースのスケールを求められませんでした。" },
	{ "Cover a larger area, or turn off Solve playspace scale in Settings.",
		"もっと広い範囲を動かすか、設定で「プレイスペースのスケールを推定」をオフにしてください。" },
	{ "Something went wrong inside QuestCalibrator.", "QuestCalibrator 内部で問題が発生しました。" },
	{ "Save a diagnostics file in Settings and send it with your report.",
		"設定で診断ファイルを保存し、報告に添えて送ってください。" },
	{ "The calibration result wasn't usable.", "キャリブレーション結果が使用できませんでした。" },
	{ "Try again with smooth motion around the room.", "部屋の中でなめらかに動かして、もう一度お試しください。" },

	// Why a run stopped.
	{ "Some tracking data was dropped: the PC couldn't keep up.",
		"トラッキングデータの一部が失われました。PC の処理が追いつきませんでした。" },
	{ "Try again; close capture or recording software if it repeats.",
		"もう一度お試しください。繰り返す場合は、キャプチャーや録画のソフトを閉じてください。" },
	{ "%s's tracking reset during the measurement.", "計測中に {0} のトラッキングがリセットされました。" },
	{ "Let tracking settle for a few seconds, then start again.",
		"数秒待ってトラッキングが安定してから、もう一度開始してください。" },
	{ "The reference device", "基準デバイス" },
	{ "The target device", "対象デバイス" },
	{ "QuestCalibrator can't talk to SteamVR.", "QuestCalibrator が SteamVR と通信できません。" },
	{ "Restart SteamVR. If it repeats, re-run the installer.",
		"SteamVR を再起動してください。繰り返す場合はインストーラーを再実行してください。" },
	{ "No reference device is selected.", "基準デバイスが選択されていません。" },
	{ "No target device is selected.", "対象デバイスが選択されていません。" },
	{ "Pick a device that's switched on.", "電源の入っているデバイスを選んでください。" },
	{ "%s isn't tracking.", "{0} がトラッキングされていません。" },
	{ "Check it's awake and in view of its tracking cameras or base stations, then try again.",
		"スリープしていないこと、トラッキングカメラやベースステーションから見えることを確認して、もう一度お試しください。" },
	{ "Check it's awake and visible to its base stations, then try again.",
		"スリープしていないこと、ベースステーションから見えることを確認して、もう一度お試しください。" },
	{ "A device changed tracking system as the run started.", "開始時にデバイスのトラッキングシステムが変わりました。" },
	{ "Re-pick both devices and start again.", "両方のデバイスを選び直して、もう一度開始してください。" },
	{ "SteamVR stopped reporting one of the devices.", "SteamVR がデバイスの 1 つを報告しなくなりました。" },
	{ "Wake or reconnect it, then try again.", "スリープを解除するか再接続して、もう一度お試しください。" },
	{ "The reference device must be on the headset's tracking system.",
		"基準デバイスはヘッドセットと同じトラッキングシステムである必要があります。" },
	{ "Pick the headset or one of its controllers as the reference.",
		"ヘッドセットか、そのコントローラーを基準に選んでください。" },
	{ "Lost contact with SteamVR mid-run.", "実行中に SteamVR との接続が切れました。" },
	{ "Restart SteamVR and try again.", "SteamVR を再起動して、もう一度お試しください。" },
	{ "%s was replaced by another device during the measurement.", "計測中に {0} が別のデバイスに置き換わりました。" },
	{ "Could not verify the identity of %s during the measurement.", "計測中に {0} を識別できませんでした。" },
	{ "Keep both devices powered and try again.", "両方のデバイスの電源を入れたまま、もう一度お試しください。" },
	{ "%s stopped tracking mid-run.", "実行中に {0} のトラッキングが止まりました。" },
	{ "Keep it tracking for the whole countdown.", "カウントダウンが終わるまでトラッキングを保ってください。" },
	{ "Keep it in view of its base stations for the whole countdown.",
		"カウントダウンが終わるまで、ベースステーションから見える状態を保ってください。" },
	{ "Pick a reference and a target from two different tracking systems.",
		"基準と対象は、異なる 2 つのトラッキングシステムから選んでください。" },
	{ "Anchors need the same reference and target systems as the current calibration. Pick those devices first.",
		"アンカーには現在のキャリブレーションと同じ基準・対象システムが必要です。先にそのデバイスを選んでください。" },
	{ "The headset isn't showing up in SteamVR, so the tracker position can't be measured yet.",
		"ヘッドセットが SteamVR に表示されていないため、まだトラッカーの位置を測定できません。" },
	{ "The headset tracker isn't connected. Switch it on, then try again.",
		"ヘッドセットトラッカーが接続されていません。電源を入れてからもう一度お試しください。" },

	// Field anchors.
	{ "Anchor not added", "アンカーを追加できませんでした" },
	{ "Anchor added", "アンカーを追加しました" },
	{ "This spot is too far off from your calibration for a small correction.",
		"この場所はキャリブレーションからのずれが大きく、小さな補正では対応できません。" },
	{ "Run a full calibration instead.", "代わりに通常のキャリブレーションを行ってください。" },
	{ "You already have 8 anchors.", "アンカーはすでに 8 件あります。" },
	{ "Add this one within 1 m of an existing anchor to replace it, or clear the anchors in Settings.",
		"既存のアンカーから 1 m 以内で追加すると置き換えられます。または設定でアンカーを消去してください。" },
	{ "It couldn't be saved.", "保存できませんでした。" },
	{ "Restart QuestCalibrator and try again.", "QuestCalibrator を再起動して、もう一度お試しください。" },
	{ "This spot now has its own correction, blended in as you walk around.",
		"この場所専用の補正ができました。歩き回ると滑らかに切り替わります。" },

	// ---- Runtime monitors (activity feed and VR notifications) ----
	{ "Your calibration looks off. Recalibrate.",
		"キャリブレーションがずれているようです。再キャリブレーションしてください。" },
	{ "QuestCalibrator: your calibration looks off. Recalibrate.",
		"QuestCalibrator：キャリブレーションがずれているようです。再キャリブレーションしてください。" },
	{ "A correction was too large to be safe and was skipped. If this keeps happening, recalibrate.",
		"補正量が大きすぎて安全でないため、スキップしました。繰り返し起きる場合は再キャリブレーションしてください。" },
	{ "Correction ready. Pull a trigger to apply it.", "補正の準備ができました。トリガーを引くと適用されます。" },
	{ "Trigger pulled; applying the correction.", "トリガーを確認しました。補正を適用します。" },
	{ "Continuous calibration paused: readings drifted too far from the calibration to correct safely.",
		"連続キャリブレーションを一時停止しました：測定値がキャリブレーションから大きくずれ、安全に補正できません。" },
	{ "QuestCalibrator: continuous calibration paused; readings drifted too far to correct safely. Recalibrate with the headset tracker to resume.",
		"QuestCalibrator：連続キャリブレーションを一時停止しました。ずれが大きすぎて安全に補正できません。再開するにはヘッドセットトラッカーで再キャリブレーションしてください。" },
	{ "Continuous calibration paused: readings are inconsistent with the headset tracker measurement.",
		"連続キャリブレーションを一時停止しました：測定値がヘッドセットトラッカーの測定と一致しません。" },
	{ "QuestCalibrator: continuous calibration paused; readings are inconsistent. Recalibrate with the headset tracker to resume.",
		"QuestCalibrator：連続キャリブレーションを一時停止しました。測定値が一致しません。再開するにはヘッドセットトラッカーで再キャリブレーションしてください。" },
	{ "Tracking is noisy here; continuous calibration is waiting and resumes on its own.",
		"この場所ではトラッキングが不安定なため、連続キャリブレーションは待機中です。自動で再開します。" },
	{ "QuestCalibrator: tracking is noisy here. Continuous calibration is waiting and resumes on its own.",
		"QuestCalibrator：この場所ではトラッキングが不安定です。連続キャリブレーションは待機中で、自動で再開します。" },
	{ "Continuous calibration resumed.", "連続キャリブレーションを再開しました。" },
	{ "Headset tracker not tracking; continuous calibration waiting.",
		"ヘッドセットトラッカーがトラッキングされていないため、連続キャリブレーションは待機中です。" },
	{ "Headset tracker back; continuous calibration warming up.",
		"ヘッドセットトラッカーが戻りました。連続キャリブレーションを準備中です。" },

	// ---- Chaperone ----
	{ "Check your room boundaries", "部屋の境界を確認してください" },
	{ "QuestCalibrator saves and restores your SteamVR chaperone. Tracking drift can still move the chaperone walls away from your real walls.",
		"QuestCalibrator は SteamVR のシャペロンを保存・復元します。それでもトラッキングのドリフトで、シャペロンの壁が実際の壁からずれることがあります。" },
	{ "Keep the Quest boundary turned on too. A protected chaperone doesn't guarantee that your play area is clear or correctly aligned.",
		"Quest の境界線もオンのままにしてください。シャペロンを保護しても、プレイエリアに障害物がないことや位置が正しいことは保証されません。" },
	{ "Before playing, check that the chaperone walls match your room and leave enough space to move safely, especially when dancing.",
		"プレイ前に、シャペロンの壁が部屋と合っていて、安全に動ける十分なスペースがあるか確認してください。ダンスをするときは特に注意してください。" },
	{ "Protect chaperone (%d s)", "シャペロンを保護（{0} 秒）" },
	{ "Chaperone saved without walls, so auto-restore stays off until Room Setup adds some.",
		"壁なしでシャペロンを保存したため、ルームセットアップで壁を追加するまで自動復元はオフのままです。" },
	{ "Chaperone saved: %u wall%s, %.1f x %.1f m.", "シャペロンを保存しました：壁 {0} 面、{2} × {3} m。" },
	{ "Chaperone restored.", "シャペロンを復元しました。" },
	{ "Couldn't check the protected chaperone: SteamVR's chaperone setup isn't available right now.",
		"保護したシャペロンを確認できませんでした：現在 SteamVR のシャペロン設定を使用できません。" },
	{ "Couldn't read the current chaperone, so the protected one wasn't changed.",
		"現在のシャペロンを読み取れなかったため、保護したシャペロンは変更していません。" },
	{ "The protected chaperone was saved for a different headset, so it was switched off. Press Protect chaperone again on the main screen.",
		"保護したシャペロンは別のヘッドセット用に保存されていたため、オフにしました。メイン画面で「シャペロンを保護」をもう一度押してください。" },
	{ "The protected chaperone is missing information about the room it was saved in, so it was switched off. Press Protect chaperone again on the main screen.",
		"保護したシャペロンに保存時の部屋の情報がないため、オフにしました。メイン画面で「シャペロンを保護」をもう一度押してください。" },
	{ "The headset re-centered, so the protected chaperone no longer lines up and was turned off. Protect it again from the main screen.",
		"ヘッドセットが再センタリングされ、保護したシャペロンの位置が合わなくなったため、オフにしました。メイン画面からもう一度保護してください。" },
	{ "The headset re-centered while QuestCalibrator couldn't follow it, so the protected chaperone was switched off. Press Protect chaperone again on the main screen.",
		"QuestCalibrator が追跡できない間にヘッドセットが再センタリングされたため、保護したシャペロンをオフにしました。メイン画面で「シャペロンを保護」をもう一度押してください。" },
	{ "The protected chaperone belonged to the previous calibration and was turned off. Protect it again from the main screen.",
		"保護したシャペロンは以前のキャリブレーションのものだったため、オフにしました。メイン画面からもう一度保護してください。" },
	{ "A headset re-center was too large to compensate safely. Recalibrate before continuing.",
		"ヘッドセットの再センタリングが大きすぎて、安全に補正できません。続ける前に再キャリブレーションしてください。" },
	{ "The headset re-centered while QuestCalibrator couldn't follow it. The calibration and the protected chaperone are off until you recalibrate.",
		"QuestCalibrator が追跡できない間にヘッドセットが再センタリングされました。再キャリブレーションするまで、キャリブレーションと保護したシャペロンはオフです。" },
	{ "The headset re-centered while QuestCalibrator couldn't follow it. The calibration is off until you recalibrate.",
		"QuestCalibrator が追跡できない間にヘッドセットが再センタリングされました。再キャリブレーションするまで、キャリブレーションはオフです。" },
	{ "Couldn't protect the chaperone. The headset re-centered since the last calibration. Recalibrate first.",
		"シャペロンを保護できませんでした。前回のキャリブレーション以降にヘッドセットが再センタリングされています。先に再キャリブレーションしてください。" },
	{ "Couldn't protect the chaperone because SteamVR's chaperone isn't available. Restart SteamVR and try again.",
		"SteamVR のシャペロンを使用できないため、シャペロンを保護できませんでした。SteamVR を再起動して、もう一度お試しください。" },
	{ "Couldn't protect the chaperone because the headset isn't showing up in SteamVR. Try again once it's connected.",
		"ヘッドセットが SteamVR に表示されていないため、シャペロンを保護できませんでした。接続してからもう一度お試しください。" },
	{ "Couldn't protect the chaperone. The calibration was made with a different headset system. Recalibrate first.",
		"シャペロンを保護できませんでした。キャリブレーションが別のヘッドセットシステムで行われています。先に再キャリブレーションしてください。" },
	{ "Couldn't protect the chaperone because the headset isn't tracking yet. Put it on and try again.",
		"ヘッドセットがまだトラッキングされていないため、シャペロンを保護できませんでした。装着してもう一度お試しください。" },
	{ "Couldn't read the chaperone walls from SteamVR. Try again.",
		"SteamVR からシャペロンの壁を読み取れませんでした。もう一度お試しください。" },
	{ "The chaperone changed while it was being saved. Try again.",
		"保存中にシャペロンが変更されました。もう一度お試しください。" },
	{ "Couldn't protect the chaperone because SteamVR has no usable play area. Set up your room in SteamVR, then try again.",
		"SteamVR に使用できるプレイエリアがないため、シャペロンを保護できませんでした。SteamVR でルームをセットアップしてから、もう一度お試しください。" },
	{ "Couldn't protect the chaperone because the PC clock looks wrong. Check the date and time, then try again.",
		"PC の時計が正しくないようなので、シャペロンを保護できませんでした。日付と時刻を確認して、もう一度お試しください。" },
	{ "Couldn't protect the chaperone because the previous one couldn't be switched off first, so nothing was changed.",
		"以前のシャペロンを先にオフにできなかったため、シャペロンを保護できませんでした。何も変更していません。" },
	{ "Couldn't restore the chaperone: the protected chaperone is damaged. Protect it again.",
		"シャペロンを復元できませんでした：保護したシャペロンが破損しています。もう一度保護してください。" },
	{ "Couldn't restore the chaperone: the headset isn't reporting to SteamVR yet.",
		"シャペロンを復元できませんでした：ヘッドセットがまだ SteamVR に認識されていません。" },
	{ "Couldn't restore the chaperone yet: the headset hasn't been tracked this session. Put it on and try again.",
		"まだシャペロンを復元できません：このセッションでヘッドセットがトラッキングされていません。装着してもう一度お試しください。" },
	{ "Couldn't restore the chaperone: SteamVR's chaperone setup isn't available right now.",
		"シャペロンを復元できませんでした：現在 SteamVR のシャペロン設定を使用できません。" },
	{ "Couldn't restore the chaperone: SteamVR rejected the update.",
		"シャペロンを復元できませんでした：SteamVR が更新を拒否しました。" },
	{ "Couldn't verify the restored chaperone. Check it in SteamVR Room Setup before relying on it.",
		"復元したシャペロンを確認できませんでした。使う前に SteamVR のルームセットアップで確認してください。" },
	{ "The calibration profile and protected chaperone were saved at different revisions. Chaperone auto-restore is disabled until you capture it again.",
		"キャリブレーションと保護したシャペロンが別々のタイミングで保存されていました。もう一度保護するまで、シャペロンの自動復元は無効です。" },
	{ "The protected chaperone has no complete headset/universe baseline. It has been disarmed; capture it again before enabling auto-restore.",
		"保護したシャペロンにヘッドセットの基準情報が揃っていないため、無効にしました。自動復元を有効にする前に、もう一度保護してください。" },
	{ "The protected chaperone belongs to a different reference tracking system. It has been disarmed; capture it again for this profile.",
		"保護したシャペロンは別の基準トラッキングシステムのものです。無効にしたので、このプロファイル用にもう一度保護してください。" },

	// ---- Saving and loading ----
	{ "Couldn't clear the calibration, so it's still saved. Restart QuestCalibrator and try again.",
		"キャリブレーションを消去できなかったため、保存されたままです。QuestCalibrator を再起動して、もう一度お試しください。" },
	{ "Couldn't read the saved calibration, so it was left as it is. Restart QuestCalibrator. If this repeats, save a diagnostics file in Settings and report it.",
		"保存されたキャリブレーションを読み取れなかったため、そのままにしています。QuestCalibrator を再起動してください。繰り返す場合は、設定で診断ファイルを保存して報告してください。" },
	{ "Couldn't read QuestCalibrator's settings, so they were left as they are. Restart QuestCalibrator. If this repeats, save a diagnostics file in Settings and report it.",
		"QuestCalibrator の設定を読み取れなかったため、そのままにしています。QuestCalibrator を再起動してください。繰り返す場合は、設定で診断ファイルを保存して報告してください。" },
	{ "Couldn't save the calibration because the saved one couldn't be read. It was left untouched so it can be recovered.",
		"保存済みのキャリブレーションを読み取れないため、保存できませんでした。復旧できるよう、そのままにしています。" },
	{ "Couldn't save the calibration because QuestCalibrator's settings couldn't be read. They were left untouched so they can be recovered.",
		"QuestCalibrator の設定を読み取れないため、キャリブレーションを保存できませんでした。復旧できるよう、設定はそのままにしています。" },
	{ "Couldn't save the calibration because settings from an older version haven't been moved over safely yet. Restart QuestCalibrator and try again.",
		"以前のバージョンの設定がまだ安全に移行されていないため、キャリブレーションを保存できませんでした。QuestCalibrator を再起動して、もう一度お試しください。" },
	{ "Couldn't save the calibration because it failed a safety check. Recalibrate.",
		"安全チェックに通らなかったため、キャリブレーションを保存できませんでした。再キャリブレーションしてください。" },
	{ "Couldn't save the calibration. It will be lost when QuestCalibrator closes.",
		"キャリブレーションを保存できませんでした。QuestCalibrator を閉じると失われます。" },
	{ "Couldn't save the calibration because the rotation values aren't valid.",
		"回転の値が無効なため、キャリブレーションを保存できませんでした。" },
	{ "Couldn't save QuestCalibrator's settings because the saved calibration couldn't be read. Nothing was changed, so both can still be recovered.",
		"保存されたキャリブレーションを読み取れないため、設定を保存できませんでした。何も変更していないので、どちらも復旧できます。" },
	{ "Couldn't save QuestCalibrator's settings because the saved ones couldn't be read. They were left untouched so they can be recovered.",
		"保存済みの設定を読み取れないため、設定を保存できませんでした。復旧できるよう、そのままにしています。" },
	{ "Couldn't save QuestCalibrator's settings because the protected chaperone failed a safety check. Protect it again.",
		"保護したシャペロンが安全チェックに通らなかったため、設定を保存できませんでした。もう一度保護してください。" },
	{ "Couldn't save QuestCalibrator's settings. Changes will be lost when it closes.",
		"設定を保存できませんでした。閉じると変更は失われます。" },
	{ "Error loading calibration profile: %s", "キャリブレーションの読み込みエラー：{0}" },
	{ "Error loading application settings: %s", "設定の読み込みエラー：{0}" },
	{ "The profile is preserved, not overwritten.", "プロファイルは上書きされず、そのまま残っています。" },
	{ "Settings changes will not save until this is fixed.", "これが直るまで、設定の変更は保存されません。" },
	{ "To start over, delete the Config value under %s", "最初からやり直すには、{0} の Config 値を削除してください" },
	{ "To start over, delete the Settings value under %s", "最初からやり直すには、{0} の Settings 値を削除してください" },
	{ "The live profile has invalid tracking-system identities and was disabled before sending it to the driver",
		"現在のプロファイルのトラッキングシステム情報が無効なため、ドライバーに送る前に無効化しました" },
	{ "The live calibration contains invalid numeric values and was disabled before sending it to the driver",
		"現在のキャリブレーションに無効な数値が含まれていたため、ドライバーに送る前に無効化しました" },
	{ "Couldn't find the local application data folder.", "ローカルのアプリケーションデータフォルダーが見つかりませんでした。" },
	{ "Couldn't create the diagnostics file in %s.", "{0} に診断ファイルを作成できませんでした。" },
	{ "Couldn't finish writing the diagnostics file.", "診断ファイルの書き込みを完了できませんでした。" },

	// ---- Updates ----
	{ "QuestCalibrator %s is a prerelease. Automatic updates follow stable releases only, so this build will not update itself. Install a stable release by hand to rejoin them.",
		"QuestCalibrator {0} はプレリリース版です。自動アップデートは安定版のみが対象のため、このビルドは自動更新されません。安定版を手動でインストールすると自動アップデートに戻れます。" },
	{ "Checking GitHub for updates", "GitHub でアップデートを確認中" },
	{ "QuestCalibrator is up to date", "QuestCalibrator は最新です" },
	{ "Downloading QuestCalibrator %s", "QuestCalibrator {0} をダウンロード中" },
	{ "QuestCalibrator %s is ready to install", "QuestCalibrator {0} をインストールできます" },
	{ "The update check could not start.", "アップデートの確認を開始できませんでした。" },
	{ "The update check failed unexpectedly.", "アップデートの確認が予期せず失敗しました。" },
	{ "Update check cancelled.", "アップデートの確認をキャンセルしました。" },
	{ "Update download cancelled.", "アップデートのダウンロードをキャンセルしました。" },
	{ "%s failed (Windows error %s).", "{0}に失敗しました（Windows エラー {1}）。" },
	{ "Opening the update connection", "アップデート用の接続" },
	{ "Setting update timeouts", "タイムアウトの設定" },
	{ "Connecting to GitHub", "GitHub への接続" },
	{ "Creating the GitHub request", "GitHub へのリクエスト作成" },
	{ "Securing GitHub redirects", "GitHub リダイレクトの保護" },
	{ "Requesting the update", "アップデートの要求" },
	{ "Reading the update response", "応答の読み取り" },
	{ "Downloading the update package", "パッケージのダウンロード" },
	{ "Starting the update helper", "アップデートヘルパーの起動" },
	{ "GitHub returned HTTP %d.", "GitHub が HTTP {0} を返しました。" },
	{ "GitHub returned invalid UTF-8.", "GitHub から不正な UTF-8 が返されました。" },
	{ "GitHub returned an invalid release list.", "GitHub から無効なリリース一覧が返されました。" },
	{ "GitHub returned an unexpectedly large release list.", "GitHub から想定外に大きいリリース一覧が返されました。" },
	{ "Windows did not provide a local app-data folder.", "Windows がローカルアプリデータフォルダーを返しませんでした。" },
	{ "Windows PowerShell could not be located.", "Windows PowerShell が見つかりませんでした。" },
	{ "The release package URL is invalid.", "リリースパッケージの URL が無効です。" },
	{ "The release package URL is not HTTPS.", "リリースパッケージの URL が HTTPS ではありません。" },
	{ "The release package URL does not use github.com.", "リリースパッケージの URL が github.com ではありません。" },
	{ "The release package digest is invalid.", "リリースパッケージのダイジェストが無効です。" },
	{ "The update package could not be saved.", "アップデートパッケージを保存できませんでした。" },
	{ "The update package is larger than GitHub reported.", "アップデートパッケージが GitHub の報告より大きいです。" },
	{ "The update package download was incomplete.", "アップデートパッケージのダウンロードが不完全です。" },
	{ "The update path contains an unsupported character.", "アップデートのパスに使用できない文字が含まれています。" },
	{ "The update folder could not be created (system error %d).", "アップデートフォルダーを作成できませんでした（システムエラー {0}）。" },
	{ "The downloaded package failed SHA-256 verification.", "ダウンロードしたパッケージが SHA-256 検証に失敗しました。" },
	{ "The verified update package could not be saved (system error %d).",
		"検証済みのアップデートパッケージを保存できませんでした（システムエラー {0}）。" },
	{ "No verified update is ready to install.", "インストールできる検証済みのアップデートがありません。" },
	{ "The downloaded update no longer passes SHA-256 verification.", "ダウンロードしたアップデートが SHA-256 検証に通らなくなりました。" },
	{ "The update helper could not be created.", "アップデートヘルパーを作成できませんでした。" },
	{ "The newest release has no trusted release page.", "最新リリースに信頼できるリリースページがありません。" },
	{ "The newest release points outside the QuestCalibrator repository.", "最新リリースが QuestCalibrator のリポジトリ外を指しています。" },
	{ "The newest release has no install package.", "最新リリースにインストールパッケージがありません。" },
	{ "The newest release contains duplicate install packages.", "最新リリースのインストールパッケージが重複しています。" },
	{ "The newest release does not contain %s.", "最新リリースに {0} が含まれていません。" },
	{ "The newest release package has invalid metadata.", "最新リリースのパッケージ情報が無効です。" },
	{ "The newest release package has no valid SHA-256 digest.", "最新リリースのパッケージに有効な SHA-256 ダイジェストがありません。" },
	{ "The newest release package points outside the QuestCalibrator repository.",
		"最新リリースのパッケージが QuestCalibrator のリポジトリ外を指しています。" },

	// ---- Lighthouse tab ----
	{ "No Lighthouse devices", "Lighthouse デバイスがありません" },
	{ "Turn on a tracker or controller that uses base stations.",
		"ベースステーションを使うトラッカーかコントローラーの電源を入れてください。" },
	{ "Waiting for SteamVR's log", "SteamVR のログを待っています" },
	{ "Base stations appear here once SteamVR has written %s", "SteamVR が {0} を書き込むと、ここにベースステーションが表示されます" },
	{ "its vrserver log.", "vrserver のログ" },
	{ "BASE STATIONS", "ベースステーション" },
	{ "None named yet. Each base station appears as SteamVR reports it.",
		"まだありません。SteamVR が報告すると、ベースステーションが表示されます。" },
	{ "id not logged yet", "ID 未記録" },
	{ "No reports yet", "報告なし" },
	{ "Seen by %d of %d", "{1} 台中 {0} 台から見えています" },
	{ "No dropouts this session", "このセッションで途切れなし" },
	{ "Dropped out %u time%s", "途切れ {0} 回" },
	{ "Dropped out %u time%s · the last one left %u time%s", "途切れ {0} 回・最後の 1 基として {2} 回" },
	{ "IN VIEW OF EACH DEVICE", "デバイスごとの見通し" },
	{ "Not in the log yet", "ログにまだありません" },
	{ "%d of %d in view", "{0}/{1} 基が見える" },
	{ "no dropouts", "途切れなし" },
	{ "%u dropout%s", "途切れ {0} 回" },
	{ "%u dropout%s, %u full loss%s", "途切れ {0} 回、完全喪失 {2} 回" },
	{ "In view: no base station", "見えている：ベースステーションなし" },
	{ "In view: %s", "見えている：{0}" },
	{ "Last change: %s", "最後の変化：{0}" },
	{ "Tracking restarted %u time%s", "トラッキング再開始 {0} 回" },
	// What last happened to a device, from LighthouseVisibility.
	{ "tracking again from %s", "{0} からトラッキング再開" },
	{ "back to %d stations with %s", "{1} が戻り {0} 基に復帰" },
	{ "lost its last station %s", "最後の {0} を失った" },
	{ "down to one station %s after losing %s", "{1} を失い {0} の 1 基のみ" },
	{ "sees no base station", "ベースステーションが見えない" },
	{ "started a new solution from %s", "{0} から新たにトラッキングを開始" },
	{ "could not start tracking from %s", "{0} からトラッキングを開始できなかった" },
	{ "Japanese", "日本語" },
	{ "Italiano", "Italiano" },
	// Names shown as they are.
	{ "VividNightmareUnleashed", "VividNightmareUnleashed" },
	{ "Jinxxy", "Jinxxy" },
	{ "OpenVR-SpaceCalibrator", "OpenVR-SpaceCalibrator" },
	{ "1 drift check this session was skipped because a base station had just changed.",
		"ベースステーションが変化した直後だったため、このセッションでドリフト確認を 1 回スキップしました。" },
	{ "%u drift checks this session were skipped because a base station had just changed.",
		"ベースステーションが変化した直後だったため、このセッションでドリフト確認を {0} 回スキップしました。" },
	{ "Base station changes haven't affected drift checks this session.",
		"このセッションでは、ベースステーションの変化はドリフト確認に影響していません。" },
	{ "Read from %s", "読み込み元：{0}" },

	// License agreement screen. The agreement itself is English only, so
	// the section names keep its English headings.
	{ "License agreement", "使用許諾契約" },
	{ "QuestCalibrator is free to use under this agreement. Read it, then agree to continue.",
		"QuestCalibrator はこの契約のもとで無料で使えます。お読みのうえ、同意して続けてください。" },
	{ "The agreement is in English only.", "契約書は英語のみです。" },
	{ "The license agreement couldn't load. Reinstall QuestCalibrator to restore it.",
		"使用許諾契約を読み込めませんでした。QuestCalibrator を再インストールして復元してください。" },
	{ "I specifically approve sections 2 (Restrictions), 6 (Termination) and 8 (Limitation of liability).",
		"第 2 条（Restrictions）、第 6 条（Termination）、第 8 条（Limitation of liability）を個別に承認します。" },
	{ "Decline and quit", "同意せずに終了" },
	{ "Agree and continue", "同意して続ける" },
	{ "Couldn't save your agreement to the license, so QuestCalibrator will ask again next time it starts.",
		"使用許諾への同意を保存できなかったため、次回の起動時に QuestCalibrator がもう一度確認します。" },
};

const size_t kJapaneseCount = sizeof kJapanese / sizeof kJapanese[0];

} // namespace questcal::i18n
